import { Prisma, type PrismaClient } from "@prisma/client";
import type { StagingSyncTask, StagingSyncTaskRepository } from "./sync-task";
const fromRow = (row: { organizationId: string; connectedSourceId: string; syncIntentId: string; executionId: string; deterministicTaskName: string; status: "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED"; attempts: number; failureCode: string | null }): StagingSyncTask => ({ organizationId: row.organizationId, connectedSourceId: row.connectedSourceId, syncIntentId: row.syncIntentId, executionId: row.executionId, name: row.deterministicTaskName, status: row.status, attempts: row.attempts, failureCode: row.failureCode ?? undefined });
export class PrismaStagingSyncTaskRepository implements StagingSyncTaskRepository {
  constructor(private readonly client: PrismaClient) {}
  async create(task: StagingSyncTask) { try { return { created: true, task: fromRow(await this.client.stagingSyncTask.create({ data: { organizationId: task.organizationId, connectedSourceId: task.connectedSourceId, syncIntentId: task.syncIntentId, executionId: task.executionId, deterministicTaskName: task.name } })) }; } catch (error) { if (!(error instanceof Prisma.PrismaClientKnownRequestError) || error.code !== "P2002") throw error; const row = await this.client.stagingSyncTask.findFirstOrThrow({ where: { OR: [{ deterministicTaskName: task.name }, { organizationId: task.organizationId, syncIntentId: task.syncIntentId }] } }); return { created: false, task: fromRow(row) }; } }
  async claim(name: string) { const updated = await this.client.stagingSyncTask.updateMany({ where: { deterministicTaskName: name, status: "PENDING" }, data: { status: "RUNNING", attempts: { increment: 1 }, startedAt: new Date() } }); const row = await this.client.stagingSyncTask.findUnique({ where: { deterministicTaskName: name } }); return row ? { claimed: updated.count === 1, task: fromRow(row) } : null; }
  async complete(name: string, status: "SUCCEEDED" | "FAILED", failureCode?: string) { const updated = await this.client.stagingSyncTask.updateMany({ where: { deterministicTaskName: name, status: "RUNNING" }, data: { status, failureCode: failureCode ?? null, completedAt: new Date() } }); if (updated.count !== 1) throw new Error("STAGING_TASK_STATE_CONFLICT"); return fromRow(await this.client.stagingSyncTask.findUniqueOrThrow({ where: { deterministicTaskName: name } })); }
}
