import { Prisma, type PrismaClient } from "@prisma/client";
import type { StagingAsyncProbeTask, StagingAsyncProbeRepository } from "./async-probe";

const fromRow = (row: { organizationId: string; probeId: string; deterministicTaskName: string; status: "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED"; attempts: number; failureCode: string | null; startedAt?: Date | null }): StagingAsyncProbeTask => ({ organizationId: row.organizationId, probeId: row.probeId, name: row.deterministicTaskName, status: row.status, attempts: row.attempts, failureCode: row.failureCode ?? undefined, startedAt: row.startedAt?.toISOString() });

export class PrismaStagingAsyncProbeRepository implements StagingAsyncProbeRepository {
  constructor(private readonly client: PrismaClient) {}
  async create(task: StagingAsyncProbeTask) { try { return { created: true, task: fromRow(await this.client.stagingAsyncProbe.create({ data: { organizationId: task.organizationId, probeId: task.probeId, deterministicTaskName: task.name } })) }; } catch (error) { if (!(error instanceof Prisma.PrismaClientKnownRequestError) || error.code !== "P2002") throw error; const row = await this.client.stagingAsyncProbe.findFirstOrThrow({ where: { OR: [{ deterministicTaskName: task.name }, { organizationId: task.organizationId, probeId: task.probeId }] } }); return { created: false, task: fromRow(row) }; } }
  async claim(name: string) { const now = new Date(); const leaseExpired = new Date(now.getTime() - 10 * 60_000); const updated = await this.client.stagingAsyncProbe.updateMany({ where: { deterministicTaskName: name, OR: [{ status: "PENDING" }, { status: "RUNNING", startedAt: { lt: leaseExpired } }] }, data: { status: "RUNNING", attempts: { increment: 1 }, startedAt: now } }); const row = await this.client.stagingAsyncProbe.findUnique({ where: { deterministicTaskName: name } }); return row ? { claimed: updated.count === 1, task: fromRow(row) } : null; }
  async complete(name: string, status: "SUCCEEDED" | "FAILED", failureCode?: string) { const updated = await this.client.stagingAsyncProbe.updateMany({ where: { deterministicTaskName: name, status: "RUNNING" }, data: { status, failureCode: failureCode ?? null, completedAt: new Date() } }); if (updated.count !== 1) throw new Error("STAGING_PROBE_STATE_CONFLICT"); return fromRow(await this.client.stagingAsyncProbe.findUniqueOrThrow({ where: { deterministicTaskName: name } })); }
}
