import { describe, expect, it, vi } from "vitest";
import { VercelWifCloudRunIdentityProvider } from "./wif";
const jwt = (payload: object) => `${Buffer.from(JSON.stringify({ alg: "RS256" })).toString("base64url")}.${Buffer.from(JSON.stringify(payload)).toString("base64url")}.signature`;
const configuration = { issuer: "https://oidc.vercel.com/team", externalAudience: "https://vercel.com/team", subject: "owner:team:project:recoveria:environment:production", workloadIdentityProvider: "//iam.googleapis.com/projects/1/locations/global/workloadIdentityPools/p/providers/v", serviceAccount: "runtime@example.iam.gserviceaccount.com", cloudRunAudience: "https://api.example.run.app" };
describe("Vercel WIF Cloud Run identity", () => {
  it("exchanges then impersonates and never returns the Vercel assertion", async () => { const now = 1_000_000; const assertion = jwt({ iss: configuration.issuer, aud: configuration.externalAudience, sub: configuration.subject, exp: 2000 }); const id = jwt({ aud: configuration.cloudRunAudience, exp: 2000 }); const fetcher = vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({ access_token: "federated", token_type: "Bearer", expires_in: 600 }), { status: 200 })).mockResolvedValueOnce(new Response(JSON.stringify({ token: id }), { status: 200 })); await expect(new VercelWifCloudRunIdentityProvider(configuration, fetcher, () => now).getIdToken(assertion)).resolves.toEqual({ token: id, audience: configuration.cloudRunAudience, expiresAt: 2_000_000 }); expect(fetcher).toHaveBeenCalledTimes(2); expect(JSON.stringify(await fetcher.mock.calls[1])).not.toContain(assertion); });
  it.each([["issuer", { iss: "evil" }], ["audience", { aud: "evil" }], ["subject", { sub: "evil" }], ["expired", { exp: 1 }]] as Array<[string, Record<string, string | number>]>) ("rejects wrong %s before STS", async (_name, override) => { const fetcher = vi.fn(); const assertion = jwt({ iss: configuration.issuer, aud: configuration.externalAudience, sub: configuration.subject, exp: 2000, ...override }); await expect(new VercelWifCloudRunIdentityProvider(configuration, fetcher, () => 1_000_000).getIdToken(assertion)).rejects.toThrow("WIF_ASSERTION_REJECTED"); expect(fetcher).not.toHaveBeenCalled(); });
  it("fails closed on STS, impersonation, malformed and wrong-audience tokens", async () => { const assertion = jwt({ iss: configuration.issuer, aud: configuration.externalAudience, sub: configuration.subject, exp: 2000 }); const cases = [[new Response("", { status: 403 })], [new Response(JSON.stringify({ access_token: "f", token_type: "Bearer", expires_in: 600 })), new Response("", { status: 403 })], [new Response(JSON.stringify({ access_token: "f", token_type: "Bearer", expires_in: 600 })), new Response(JSON.stringify({ token: "bad" }))], [new Response(JSON.stringify({ access_token: "f", token_type: "Bearer", expires_in: 600 })), new Response(JSON.stringify({ token: jwt({ aud: "wrong", exp: 2000 }) }))]]; for (const responses of cases) { const fetcher = vi.fn(); for (const response of responses) fetcher.mockResolvedValueOnce(response); await expect(new VercelWifCloudRunIdentityProvider(configuration, fetcher, () => 1_000_000).getIdToken(assertion)).rejects.toThrow(); } });
});
