import{access,readdir}from"node:fs/promises";import path from"node:path";import{describe,expect,it}from"vitest";import{syntheticClientZeroDryRun}from"./dry-run";import{CLIENT_ZERO_MANIFEST_FIELDS}from"./manifest";import{activateDataMode,CLIENT_ZERO_ACK}from"./mode";import{clientZeroPreflight}from"./preflight";import{sanitizedReport}from"./report";import{safeParserError,serializeSafeLog}from"./safe-logger";import{withPrivateTemp,writePrivateTemp}from"./temp";
const ROOT=process.cwd();
describe("Client Zero readiness",()=>{
 it("defaults to synthetic mode",()=>expect(activateDataMode({},ROOT)).toEqual({mode:"SYNTHETIC"}));
 it("fails closed without acknowledgement",()=>expect(()=>activateDataMode({RECOVERIA_DATA_MODE:"client-zero"},ROOT)).toThrow("CLIENT_ZERO_ACK_REQUIRED"));
 it("rejects paths outside private boundary",()=>expect(()=>activateDataMode({RECOVERIA_DATA_MODE:"client-zero",RECOVERIA_CLIENT_ZERO_ACK:CLIENT_ZERO_ACK,RECOVERIA_CLIENT_ZERO_PATH:"/tmp"},ROOT)).toThrow("CLIENT_ZERO_PATH_OUTSIDE_PRIVATE_BOUNDARY"));
 it("activates only with both controls and private path",()=>expect(activateDataMode({RECOVERIA_DATA_MODE:"client-zero",RECOVERIA_CLIENT_ZERO_ACK:CLIENT_ZERO_ACK,RECOVERIA_CLIENT_ZERO_PATH:path.join(ROOT,".private/client-zero/inbox")},ROOT).mode).toBe("CLIENT_ZERO"));
 it("verifies private boundary is ignored and untracked",()=>expect(clientZeroPreflight(ROOT)).toEqual(expect.objectContaining({ok:true,boundaryIgnored:true,trackedPrivateFiles:[]})));
 it("allowlists safe logs and excludes raw errors",()=>{const log=serializeSafeLog(safeParserError("doc_internal_1","PARSE",new Error("SECRET RAW CONTENT")));expect(log).toContain("doc_internal_1");expect(log).not.toContain("SECRET RAW CONTENT");});
 it("rejects unsafe log fields at the type-independent boundary",()=>expect(()=>serializeSafeLog({documentInternalId:"d",stage:"PARSE",reasonCode:"X",status:"FAILED",customerName:"secret"} as never)).toThrow("UNSAFE_LOG_FIELD"));
 it("cleans private temp after success",async()=>{let target="";await withPrivateTemp(ROOT,async dir=>{target=await writePrivateTemp(dir,"synthetic.bin",new Uint8Array([1]));await access(target);});await expect(access(target)).rejects.toThrow();});
 it("cleans private temp after failure",async()=>{let dir="";await expect(withPrivateTemp(ROOT,async d=>{dir=d;throw new Error("synthetic failure");})).rejects.toThrow();await expect(access(dir)).rejects.toThrow();});
 it("sanitizes reports to aggregate fields",()=>{const report=sanitizedReport({organizationId:"o",idempotencyKey:"k",documentsReceived:1,documentsParsed:0,invoiceCandidates:0,reviewRequired:1,duplicates:0,unsupportedDocuments:0,failures:1,results:[],duplicateFindings:[]},true);expect(Object.keys(report)).not.toEqual(expect.arrayContaining(["invoiceNumber","customerName","cuit","address"]));expect(report.screenshotsGenerated).toBe(0);});
 it("manifest contains only safe operational fields",()=>expect(CLIENT_ZERO_MANIFEST_FIELDS).toEqual(["documentInternalId","checksum","format","parserRoute","processingStatus","reviewRequired","duplicateStatus","failureReason"]));
 it("runs the exact workflow with synthetic data and leaves no temp/screenshots",async()=>{const run=await syntheticClientZeroDryRun(ROOT);expect(run.label).toContain("SYNTHETIC");expect(run.report).toEqual(expect.objectContaining({simulation:true,documentsReceived:40,screenshotsGenerated:0}));expect(run.tempArtifactsRemaining).toEqual([]);expect((await readdir(path.join(ROOT,".private/client-zero"))).includes("screenshots")).toBe(false);});
});
