import { DriveSourceFetchError, type DriveChange, type DriveChangePage, type DriveFileDescriptor, type DriveFilePage, type GoogleDriveClientPort } from "./google-drive-source-contract";

export interface FakeDriveRecord extends DriveFileDescriptor { readonly bytes: Uint8Array }
type Operation = "LIST" | "METADATA" | "READ" | "START_TOKEN" | "CHANGES";

/** Deterministic offline conformance client. It never performs I/O or network calls. */
export class FakeGoogleDriveClient implements GoogleDriveClientPort {
  readonly records = new Map<string, FakeDriveRecord>(); readonly reads = new Map<string, number>();
  readonly failures = new Map<Operation, DriveSourceFetchError[]>(); readonly invalidTokens = new Map<string, "INVALID" | "EXPIRED">();
  readonly operationCalls = new Map<Operation, number>(); readonly scheduledFailures = new Map<string, DriveSourceFetchError>();
  readonly fileNextTokens = new Map<string, string | undefined>(); readonly changeNextTokens = new Map<string, string | undefined>();
  pageSize = 50; changePageSize = 50; leakOutsideBoundary = false; #revision = 0; readonly #changes: Array<{ revision: number; change: DriveChange }> = [];
  #fail(operation: Operation): void { const call = (this.operationCalls.get(operation) ?? 0) + 1; this.operationCalls.set(operation, call); const scheduled = this.scheduledFailures.get(`${operation}:${call}`); if (scheduled) throw scheduled; const queue = this.failures.get(operation); const error = queue?.shift(); if (error) throw error; }
  failNext(operation: Operation, error: DriveSourceFetchError): void { this.failures.set(operation, [...(this.failures.get(operation) ?? []), error]); }
  failOnCall(operation: Operation, call: number, error: DriveSourceFetchError): void { this.scheduledFailures.set(`${operation}:${call}`, error); }
  put(record: FakeDriveRecord): void { this.records.set(record.fileId, record); this.#revision += 1; this.#changes.push({ revision: this.#revision, change: { fileId: record.fileId, removed: false, file: record } }); }
  remove(fileId: string): void { this.records.delete(fileId); this.#revision += 1; this.#changes.push({ revision: this.#revision, change: { fileId, removed: true } }); }
  trash(fileId: string): void { const prior = this.records.get(fileId); if (!prior) return; const record = { ...prior, trashed: true }; this.records.set(fileId, record); this.#revision += 1; this.#changes.push({ revision: this.#revision, change: { fileId, removed: false, file: record } }); }
  invalidateToken(token: string, state: "INVALID" | "EXPIRED"): void { this.invalidTokens.set(token, state); }
  async listFiles(input: { rootId: string; pageToken?: string }): Promise<DriveFilePage> { this.#fail("LIST"); const offset = input.pageToken ? Number(input.pageToken) : 0; if (!Number.isInteger(offset) || offset < 0) throw new DriveSourceFetchError("DRIVE_PAGE_TOKEN_INVALID", "TERMINAL"); const eligible = [...this.records.values()].filter((item) => this.leakOutsideBoundary || item.corpusRootId === input.rootId).sort((a, b) => a.fileId.localeCompare(b.fileId)); const files = eligible.slice(offset, offset + this.pageSize); const key = input.pageToken ?? "<START>"; const nextPageToken = this.fileNextTokens.has(key) ? this.fileNextTokens.get(key) : offset + this.pageSize < eligible.length ? String(offset + this.pageSize) : undefined; return { files, ...(nextPageToken ? { nextPageToken } : {}) }; }
  async getMetadata(fileId: string): Promise<DriveFileDescriptor> { this.#fail("METADATA"); const record = this.records.get(fileId); if (!record) throw new DriveSourceFetchError("DRIVE_FILE_NOT_FOUND", "TERMINAL"); return record; }
  async readPdfContent(fileId: string): Promise<Uint8Array> { this.#fail("READ"); const record = this.records.get(fileId); if (!record) throw new DriveSourceFetchError("DRIVE_FILE_NOT_FOUND", "TERMINAL"); if (record.mimeType !== "application/pdf") throw new DriveSourceFetchError("DRIVE_UNSUPPORTED_MIME", "TERMINAL"); this.reads.set(fileId, (this.reads.get(fileId) ?? 0) + 1); return record.bytes; }
  async getStartPageToken(): Promise<string> { this.#fail("START_TOKEN"); return `token-${this.#revision}`; }
  async listChanges(input: { rootId: string; pageToken: string }): Promise<DriveChangePage> { this.#fail("CHANGES"); const invalid = this.invalidTokens.get(input.pageToken); if (invalid) throw new DriveSourceFetchError(`DRIVE_CURSOR_${invalid}`, invalid === "EXPIRED" ? "CURSOR_EXPIRED" : "CURSOR_INVALID"); const match = /^token-(\d+)(?::(\d+))?$/.exec(input.pageToken); if (!match) throw new DriveSourceFetchError("DRIVE_CURSOR_INVALID", "CURSOR_INVALID"); const since = Number(match[1]); const offset = Number(match[2] ?? 0); const eligible = this.#changes.filter(({ revision, change }) => revision > since && (!change.file || change.file.corpusRootId === input.rootId)); const slice = eligible.slice(offset, offset + this.changePageSize).map(({ change }) => change); const more = offset + this.changePageSize < eligible.length; const naturalNext = more ? `token-${since}:${offset + this.changePageSize}` : undefined; const nextPageToken = this.changeNextTokens.has(input.pageToken) ? this.changeNextTokens.get(input.pageToken) : naturalNext; return { changes: slice, ...(nextPageToken ? { nextPageToken } : { newStartPageToken: `token-${this.#revision}` }) }; }
}
