import { describe, expect, it } from "vitest";
import { InMemoryConnectionLifecycleRepository, parsePilotActivationConfiguration } from "./google-drive-activation";
import { GOOGLE_DRIVE_READONLY_SCOPE, type DownloadSecurityEvent } from "./google-drive-pilot-infrastructure";
import { InMemoryPilotExecutionRepository, OneShotGoogleDrivePilotOrchestrator, type DurableCheckpointPort } from "./google-drive-durable-runtime";
import { DeterministicDocumentUnderstandingProvider, type DocumentUnderstandingProvider } from "./document-understanding-provider";
import { composeRealGoogleDrivePilot, parseRealPilotCompositionConfiguration, RealGoogleDrivePilotRuntimeDriver, SingleAttemptSignalBindingTransport, WiredGoogleDrivePilotService } from "./google-drive-real-pilot-wiring";
import { GOOGLE_DRIVE_RETRY_MODE, GoogleDriveTransportError, RealGoogleDriveClient, type DeclaredGoogleDriveTransport, type GoogleDriveOperation, type GoogleDriveTransport, type GoogleDriveTransportRequest } from "./real-google-drive-client";
import { RetryingGoogleDriveTransport } from "./google-drive-pilot-infrastructure";
import type { DurableGoogleDriveCallbackRuntime } from "./google-drive-durable-runtime";
import { IncrementalCorpusProcessor, type SourceCheckpoint } from "./incremental-corpus-processor";
import { createCloudRunCallbackHandler, GOOGLE_OAUTH_CALLBACK_ISSUER, GOOGLE_OAUTH_CALLBACK_SCOPE } from "./google-drive-cloud-adapters";
import { buildSyntheticDrivePilotCorpus, changedSyntheticDrivePilotFile } from "../../test/fixtures/google-drive-synthetic-pilot-corpus";

const configuration = () => parsePilotActivationConfiguration({ ACTIVATION_ENABLED: "true", GOOGLE_CLIENT_ID: "synthetic-client", GOOGLE_CLIENT_SECRET_REFERENCE: "projects/p/secrets/oauth/versions/1", EXACT_CALLBACK_URL: "https://pilot.example.test/oauth/callback", REQUIRED_SCOPE: GOOGLE_DRIVE_READONLY_SCOPE, ORGANIZATION_ID: "org", CONNECTION_ID: "connection", AUTHORIZED_ROOT_ID: "root", EXPECTED_CORPUS_SIZE: "40", HARD_MAXIMUM_DOWNLOADS: "50", MAXIMUM_EXPANSION_RATIO: "1.25", MAXIMUM_PDF_BYTES: "26214400", MAXIMUM_PAGES: "10", MAXIMUM_RETRY_ATTEMPTS: "3", MAXIMUM_EXECUTION_DURATION_MS: "300000", AUDIT_PERSISTENCE_CONFIGURED: "true", CREDENTIAL_VAULT_CONFIGURED: "true", CHECKPOINT_PERSISTENCE_CONFIGURED: "true", OAUTH_PROVIDER_CONFIGURED: "true", ENCRYPTION_CONFIGURED: "true" });
const invocation = { operatorConfirmed: true as const, organizationId: "org", connectionId: "connection", authorizedRootId: "root", configurationVersion: "test-v1" };
const root = { id: "root", name: "Root", mimeType: "application/vnd.google-apps.folder", parents: [] as string[], trashed: false };
const pdfMetadata = (id: string, bytes: Uint8Array, parents = ["root"], name = `${id}.pdf`) => ({ id, name, mimeType: "application/pdf", size: String(bytes.byteLength), modifiedTime: "2026-09-20T00:00:00Z", parents, trashed: false });
function invoicePdf(number: number): Uint8Array { const lines = ["FACTURA B", `Nro: 0007-${String(number).padStart(8, "0")}`, "Fecha: 15/07/2026", "CUIT: 30-70000000-1", `Razon Social: Consorcio ${number % 6}`, `CUIT: 30-${String(80_000_000 + number % 6).padStart(8, "0")}-1`, "Moneda: Peso", `TOTAL ${100000 + number}.00`]; const commands = lines.map((line, index) => `BT /F1 10 Tf 40 ${800 - index * 22} Td (${line}) Tj ET`).join("\n"); const objects = ["<< /Type /Catalog /Pages 2 0 R >>", "<< /Type /Pages /Kids [3 0 R] /Count 1 >>", "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 600 840] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>", `<< /Length ${Buffer.byteLength(commands)} >>\nstream\n${commands}\nendstream`, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"]; let value = "%PDF-1.4\n"; const offsets = [0]; objects.forEach((body, index) => { offsets.push(Buffer.byteLength(value)); value += `${index + 1} 0 obj\n${body}\nendobj\n`; }); const xref = Buffer.byteLength(value); value += `xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(offset => `${String(offset).padStart(10, "0")} 00000 n \n`).join("")}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`; return new TextEncoder().encode(value); }

class FakeTransport implements GoogleDriveTransport {
  readonly [GOOGLE_DRIVE_RETRY_MODE] = "SINGLE_ATTEMPT" as const;
  readonly attempts = new Map<GoogleDriveOperation, number>();
  files: Record<string, unknown>[] = [];
  readonly content = new Map<string, Uint8Array>();
  readonly metadata = new Map<string, Record<string, unknown>>([["root", root]]);
  listFailures: unknown[] = [];
  downloads = 0;
  async execute<T>(request: GoogleDriveTransportRequest): Promise<T> { this.attempts.set(request.operation, (this.attempts.get(request.operation) ?? 0) + 1); if (request.signal?.aborted) throw new Error("PILOT_EXECUTION_TIMEOUT"); if (request.operation === "FILES_LIST") { const failure = this.listFailures.shift(); if (failure) throw failure; return { files: this.files } as T; } if (request.operation === "FILES_GET") { const value = this.metadata.get(String(request.parameters.fileId)); if (!value) throw new GoogleDriveTransportError(404, ["notFound"]); return value as T; } if (request.operation === "FILES_DOWNLOAD") { this.downloads += 1; return this.content.get(String(request.parameters.fileId)) as T; } throw new Error(`unexpected ${request.operation}`); }
  replace(files: Array<{ id: string; bytes: Uint8Array; parents?: string[]; name?: string }>): void { this.files = files.map(file => pdfMetadata(file.id, file.bytes, file.parents, file.name)); for (const file of this.files) this.metadata.set(String(file.id), file); this.content.clear(); for (const file of files) this.content.set(file.id, file.bytes); }
}
class MemoryCheckpoints implements DurableCheckpointPort {
  version = 0; checkpoint?: SourceCheckpoint; failSave = false;
  async available() { return true; }
  async load() { return this.checkpoint ? { version: this.version, checkpoint: this.checkpoint } : null; }
  async save(_key: unknown, _connection: string, checkpoint: SourceCheckpoint, expected: number | null) { if (this.failSave || expected !== (this.version || null)) throw new Error("CHECKPOINT_OPTIMISTIC_LOCK_CONFLICT"); this.checkpoint = checkpoint; this.version += 1; }
}
function harness(transport: FakeTransport, checkpoints = new MemoryCheckpoints(), provider: DocumentUnderstandingProvider = new DeterministicDocumentUnderstandingProvider(), auditFailure = false, bindAuditToExecution = false) { const lifecycle = new InMemoryConnectionLifecycleRepository(); lifecycle.seed({ organizationId: "org", connectionId: "connection", state: "CONNECTED", revision: 1 }); const binding = new SingleAttemptSignalBindingTransport(transport); const client = new RealGoogleDriveClient({ organizationId: "org", connectionId: "connection", googleSubject: "subject", authorizedRootId: "root", authorizationState: "CONNECTED" }, { async getValidAccessToken() { return { value: "token-sentinel" }; } }, binding); const driver = new RealGoogleDrivePilotRuntimeDriver(client, binding, "root"); const events: DownloadSecurityEvent[] = []; const auditExecutionIds: string[] = []; const executions = new InMemoryPilotExecutionRepository(); const sink = { async append(event: DownloadSecurityEvent) { if (auditFailure) throw new Error("AUDIT_UNAVAILABLE"); events.push(event); } }; const orchestrator = new OneShotGoogleDrivePilotOrchestrator(lifecycle, executions, bindAuditToExecution ? executionId => { auditExecutionIds.push(executionId); return sink; } : sink, checkpoints, driver); return { service: new WiredGoogleDrivePilotService(orchestrator, driver, new IncrementalCorpusProcessor(provider), checkpoints), driver, events, auditExecutionIds, executions, checkpoints };
}

describe("real Google Drive pilot wiring", () => {
  it("fails composition closed without concrete Secret Manager and KMS versions", () => { const source = { ACTIVATION_ENABLED: "true", GOOGLE_CLIENT_ID: "synthetic-client", GOOGLE_CLIENT_SECRET_REFERENCE: "projects/p/secrets/oauth/versions/1", EXACT_CALLBACK_URL: "https://pilot.example.test/oauth/callback", REQUIRED_SCOPE: GOOGLE_DRIVE_READONLY_SCOPE, ORGANIZATION_ID: "org", CONNECTION_ID: "connection", AUTHORIZED_ROOT_ID: "root", EXPECTED_CORPUS_SIZE: "40", HARD_MAXIMUM_DOWNLOADS: "50", MAXIMUM_EXPANSION_RATIO: "1.25", MAXIMUM_PDF_BYTES: "26214400", MAXIMUM_PAGES: "10", MAXIMUM_RETRY_ATTEMPTS: "3", MAXIMUM_EXECUTION_DURATION_MS: "300000", AUDIT_PERSISTENCE_CONFIGURED: "true", CREDENTIAL_VAULT_CONFIGURED: "true", CHECKPOINT_PERSISTENCE_CONFIGURED: "true", OAUTH_PROVIDER_CONFIGURED: "true", ENCRYPTION_CONFIGURED: "true", OPERATOR_ID: "operator", CALLBACK_PATH: "/oauth/callback", KMS_RESOURCE: "projects/p/locations/l/keyRings/r/cryptoKeys/k/cryptoKeyVersions/1" }; expect(parseRealPilotCompositionConfiguration(source)).toMatchObject({ operatorId: "operator", callbackPath: "/oauth/callback" }); expect(() => parseRealPilotCompositionConfiguration({ ...source, GOOGLE_CLIENT_SECRET_REFERENCE: "projects/p/secrets/oauth/versions/latest" })).toThrow("PILOT_CONFIG_SECRET_REFERENCE_INVALID"); expect(() => parseRealPilotCompositionConfiguration({ ...source, KMS_RESOURCE: "projects/p/locations/l/keyRings/r/cryptoKeys/k" })).toThrow("PILOT_CONFIG_KMS_RESOURCE_INVALID"); });
  it("accepts only the exact Google success contract and rejects identity injection or duplicates", async () => { const received: unknown[] = []; const handler = createCloudRunCallbackHandler("/oauth/callback", { async handle(input) { received.push(input); } }); const valid = { state: "state", code: "code", iss: GOOGLE_OAUTH_CALLBACK_ISSUER, scope: GOOGLE_OAUTH_CALLBACK_SCOPE }; const response = await handler({ method: "GET", path: "/oauth/callback", query: valid }); expect(response.status).toBe(200); expect(received).toEqual([{ state: "state", code: "code" }]); expect(response.body).not.toMatch(/state|code|attacker/); await expect(handler({ method: "GET", path: "/oauth/callback", query: { ...valid, organizationId: "attacker" } })).resolves.toMatchObject({ status: 400 }); await expect(handler({ method: "GET", path: "/oauth/callback", query: { ...valid, state: ["one", "two"] } })).resolves.toMatchObject({ status: 400 }); });
  it("has one retry owner and structurally rejects every retry-capable or undeclared delegate", async () => { const retryable = new FakeTransport(); retryable.replace([{ id: "file", bytes: invoicePdf(1) }]); retryable.listFailures = [new GoogleDriveTransportError(503), new GoogleDriveTransportError(503)]; await expect(harness(retryable).service.execute(configuration(), invocation)).resolves.toBeDefined(); expect(retryable.attempts.get("FILES_LIST")).toBe(3); const persistent = new FakeTransport(); persistent.replace([{ id: "file", bytes: invoicePdf(1) }]); persistent.listFailures = [new GoogleDriveTransportError(503), new GoogleDriveTransportError(503), new GoogleDriveTransportError(503)]; await expect(harness(persistent).service.execute(configuration(), invocation)).rejects.toBeDefined(); expect(persistent.attempts.get("FILES_LIST")).toBe(3); const terminal = new FakeTransport(); terminal.replace([{ id: "file", bytes: invoicePdf(1) }]); terminal.listFailures = [new GoogleDriveTransportError(401, ["authError"])]; await expect(harness(terminal).service.execute(configuration(), invocation)).rejects.toBeDefined(); expect(terminal.attempts.get("FILES_LIST")).toBe(1); const lowest = new FakeTransport(); const nested = new RetryingGoogleDriveTransport(lowest, { maximumAttempts: 3, baseDelayMs: 1, maximumDelayMs: 1 }, async () => undefined, () => 0); expect(() => new SingleAttemptSignalBindingTransport(nested)).toThrow("PILOT_RETRY_CAPABLE_TRANSPORT_REJECTED"); const alternative = { [GOOGLE_DRIVE_RETRY_MODE]: "RETRY_CAPABLE", async execute() { throw new Error("must not execute"); } } as unknown as DeclaredGoogleDriveTransport; expect(() => new SingleAttemptSignalBindingTransport(alternative)).toThrow("PILOT_RETRY_CAPABLE_TRANSPORT_REJECTED"); const undeclared = { async execute() { throw new Error("must not execute"); } } as unknown as DeclaredGoogleDriveTransport; expect(() => new SingleAttemptSignalBindingTransport(undeclared)).toThrow("PILOT_RETRY_SEMANTICS_UNDECLARED"); expect(lowest.attempts.size).toBe(0); });

  it("rejects composition identity mismatches before any Drive request", () => { const transport = new FakeTransport(); const source = { ACTIVATION_ENABLED: "true", GOOGLE_CLIENT_ID: "synthetic-client", GOOGLE_CLIENT_SECRET_REFERENCE: "projects/p/secrets/oauth/versions/1", EXACT_CALLBACK_URL: "https://pilot.example.test/oauth/callback", REQUIRED_SCOPE: GOOGLE_DRIVE_READONLY_SCOPE, ORGANIZATION_ID: "org", CONNECTION_ID: "connection", AUTHORIZED_ROOT_ID: "root", EXPECTED_CORPUS_SIZE: "40", HARD_MAXIMUM_DOWNLOADS: "50", MAXIMUM_EXPANSION_RATIO: "1.25", MAXIMUM_PDF_BYTES: "26214400", MAXIMUM_PAGES: "10", MAXIMUM_RETRY_ATTEMPTS: "3", MAXIMUM_EXECUTION_DURATION_MS: "300000", AUDIT_PERSISTENCE_CONFIGURED: "true", CREDENTIAL_VAULT_CONFIGURED: "true", CHECKPOINT_PERSISTENCE_CONFIGURED: "true", OAUTH_PROVIDER_CONFIGURED: "true", ENCRYPTION_CONFIGURED: "true", OPERATOR_ID: "operator", CALLBACK_PATH: "/oauth/callback", KMS_RESOURCE: "projects/p/locations/l/keyRings/r/cryptoKeys/k/cryptoKeyVersions/1" }; const base = { configuration: parseRealPilotCompositionConfiguration(source), callbackRuntime: null as unknown as DurableGoogleDriveCallbackRuntime, driveCredentials: { async getValidAccessToken() { return { value: "token" }; } }, driveTransport: transport, lifecycle: new InMemoryConnectionLifecycleRepository(), executions: new InMemoryPilotExecutionRepository(), audit: { async append() {} }, understandingProvider: new DeterministicDocumentUnderstandingProvider(), checkpoints: new MemoryCheckpoints() }; const connection = { organizationId: "org", connectionId: "connection", googleSubject: "subject", authorizedRootId: "root", authorizationState: "CONNECTED" as const }; expect(() => composeRealGoogleDrivePilot({ ...base, driveConnection: { ...connection, authorizedRootId: "other" } })).toThrow("PILOT_COMPOSITION_ROOT_MISMATCH"); expect(() => composeRealGoogleDrivePilot({ ...base, driveConnection: { ...connection, connectionId: "other" } })).toThrow("PILOT_COMPOSITION_CONNECTION_MISMATCH"); expect(() => composeRealGoogleDrivePilot({ ...base, driveConnection: { ...connection, organizationId: "other" } })).toThrow("PILOT_COMPOSITION_ORGANIZATION_MISMATCH"); expect(transport.attempts.size).toBe(0); });

  it("re-proves root membership after discovery and never downloads a moved-out file", async () => { const transport = new FakeTransport(); const bytes = invoicePdf(1); transport.replace([{ id: "file", bytes }]); const { driver } = harness(transport); await driver.listPage({ rootId: "root", signal: new AbortController().signal }); transport.metadata.set("outside", { id: "outside", name: "Outside", mimeType: "application/vnd.google-apps.folder", parents: [], trashed: false }); transport.metadata.set("file", pdfMetadata("file", bytes, ["outside"])); await expect(driver.download({ fileId: "file", maximumBytes: 1_000_000, signal: new AbortController().signal })).rejects.toBeDefined(); expect(transport.downloads).toBe(0); });

  it("rehearses the deterministic 40-PDF pilot, unchanged reuse, and incremental mutations", async () => {
    const transport = new FakeTransport();
    const corpus = buildSyntheticDrivePilotCorpus();
    const runOne = corpus.map(file => ({ id: file.id, bytes: file.bytes, name: file.fileName }));
    transport.replace(runOne);
    const delegate = new DeterministicDocumentUnderstandingProvider();
    const understood: number[] = [];
    const provider: DocumentUnderstandingProvider = { id: delegate.id, processingVersion: delegate.processingVersion, async understand(request) { understood.push(request.documents.length); return delegate.understand(request); } };
    const state = harness(transport, new MemoryCheckpoints(), provider, false, true);

    const first = await state.service.execute(configuration(), invocation);
    expect(first.execution.status).toBe("SUCCEEDED");
    expect(state.auditExecutionIds[0]).toBe(first.execution.id);
    expect(first.report.metrics).toMatchObject({ documentsDiscovered: 40, documentsUnderstood: 40, documentsReused: 0 });
    expect(first.report.summary).toMatchObject({ documentsClassifiedAsInvoice: 40, exactDuplicates: 1, identityClusters: 5, unresolvedIdentities: 0, relationshipProposals: 248, contradictions: 0, incompleteCoreDocuments: 0 });
    expect(state.checkpoints.version).toBe(1);

    transport.replace(runOne);
    const unchanged = await state.service.execute(configuration(), invocation);
    expect(unchanged.report.metrics).toMatchObject({ documentsDiscovered: 40, documentsUnderstood: 0, documentsReused: 40 });
    expect(unchanged.report.changes.every(change => change.kind === "UNCHANGED")).toBe(true);
    expect(state.checkpoints.version).toBe(2);

    const changed = changedSyntheticDrivePilotFile(corpus[10]!);
    transport.replace([
      ...runOne.slice(0, 38).map(file => file.id === corpus[0]!.id ? { ...file, name: "renombrado-misma-identidad.pdf" } : file.id === changed.id ? { id: file.id, name: file.name, bytes: changed.bytes } : file),
      { id: "synthetic-drive-new-duplicate", name: "duplicado-nuevo-origen.pdf", bytes: corpus[20]!.bytes },
    ]);
    const incremental = await state.service.execute(configuration(), invocation);
    expect(incremental.report.metrics).toMatchObject({ documentsDiscovered: 39, documentsUnderstood: 2, documentsReused: 37 });
    const changes = incremental.report.changes.map(change => change.kind);
    expect(changes).toEqual(expect.arrayContaining(["CONTENT_CHANGED", "SAME_CONTENT_DIFFERENT_SOURCE_RECORD", "REMOVED"]));
    expect(incremental.report.changes.find(change => change.sourceDocumentId === corpus[0]!.id)?.kind).toBe("UNCHANGED");
    expect(understood).toEqual([40, 2]);
    expect(state.checkpoints.version).toBe(3);
    expect(state.auditExecutionIds).toEqual([first.execution.id, unchanged.execution.id, incremental.execution.id]);
    expect(state.events[0]?.outcome).toBe("STARTED");
    expect(state.events[1]?.outcome).toBe("SUCCEEDED");
  });

  it("does not advance the prior checkpoint on audit, processing, or CAS failure", async () => { for (const failure of ["audit", "processing", "cas"] as const) { const transport = new FakeTransport(); transport.replace([{ id: "file", bytes: invoicePdf(1) }]); const checkpoints = new MemoryCheckpoints(); const initial = harness(transport, checkpoints); await initial.service.execute(configuration(), invocation); const version = checkpoints.version; transport.replace([{ id: "file", bytes: invoicePdf(2) }]); const provider = failure === "processing" ? { id: "failing", processingVersion: "v2", async understand() { throw new Error("PROVIDER_FAILED"); } } : new DeterministicDocumentUnderstandingProvider(); checkpoints.failSave = failure === "cas"; await expect(harness(transport, checkpoints, provider, failure === "audit").service.execute(configuration(), invocation)).rejects.toBeDefined(); expect(checkpoints.version).toBe(version); } });
  it("rejects a mismatched checkpoint boundary before any Drive operation", async () => { const transport = new FakeTransport(); transport.replace([{ id: "file", bytes: invoicePdf(1) }]); const checkpoints = new MemoryCheckpoints(); await harness(transport, checkpoints).service.execute(configuration(), invocation); checkpoints.checkpoint = { ...checkpoints.checkpoint!, organizationId: "other" }; transport.attempts.clear(); await expect(harness(transport, checkpoints).service.execute(configuration(), invocation)).rejects.toThrow("CHECKPOINT_SOURCE_BOUNDARY_MISMATCH"); expect(transport.attempts.size).toBe(0); });
});
