import type { IncrementalCorpusReport, IncrementalCorpusRun } from "./incremental-corpus-processor";
import { IncrementalCorpusProcessor } from "./incremental-corpus-processor";
import type { DocumentUnderstandingProvider } from "./document-understanding-provider";
import type { DiscoveredDocument, DocumentSource } from "./document-source";
import type { DriveConnection, DriveFileDescriptor } from "./google-drive-source-contract";
import { createCloudRunCallbackHandler, type CallbackHttpRequest, type CallbackHttpResponse } from "./google-drive-cloud-adapters";
import { parsePilotActivationConfiguration, type ConnectionLifecycleRepository, type ExternalActivationConfiguration, type PilotActivationConfiguration } from "./google-drive-activation";
import { OneShotGoogleDrivePilotOrchestrator, type DurableCheckpointPort, type OneShotPilotInvocation, type PilotExecutionRepository, type PilotPageDocument, type PilotRuntimeDriver } from "./google-drive-durable-runtime";
import { GOOGLE_DRIVE_RETRY_MODE, RealGoogleDriveClient, type DeclaredGoogleDriveTransport, type DriveCredentialProvider, type GoogleDriveTransportRequest } from "./real-google-drive-client";
import type { DurableGoogleDriveCallbackRuntime, RuntimeCallbackInput } from "./google-drive-durable-runtime";
import type { DownloadSecurityAuditSink } from "./google-drive-pilot-infrastructure";

export class SingleAttemptSignalBindingTransport implements DeclaredGoogleDriveTransport {
  readonly [GOOGLE_DRIVE_RETRY_MODE] = "SINGLE_ATTEMPT" as const;
  #signal?: AbortSignal;
  constructor(private readonly delegate: DeclaredGoogleDriveTransport) {
    const mode = delegate[GOOGLE_DRIVE_RETRY_MODE];
    if (mode === "RETRY_CAPABLE") throw new Error("PILOT_RETRY_CAPABLE_TRANSPORT_REJECTED");
    if (mode !== "SINGLE_ATTEMPT") throw new Error("PILOT_RETRY_SEMANTICS_UNDECLARED");
  }
  async run<T>(signal: AbortSignal, operation: () => Promise<T>): Promise<T> { if (this.#signal) throw new Error("PILOT_DRIVER_CONCURRENT_OPERATION"); this.#signal = signal; try { if (signal.aborted) throw new Error("PILOT_EXECUTION_TIMEOUT"); return await operation(); } finally { this.#signal = undefined; } }
  execute<T>(request: GoogleDriveTransportRequest): Promise<T> { return this.delegate.execute<T>({ ...request, signal: this.#signal }); }
}

export class RealGoogleDrivePilotRuntimeDriver implements PilotRuntimeDriver {
  readonly #descriptors = new Map<string, DriveFileDescriptor>(); readonly #content = new Map<string, Uint8Array>();
  constructor(private readonly client: RealGoogleDriveClient, private readonly transportBinding: SingleAttemptSignalBindingTransport, private readonly authorizedRootId: string, private readonly sharedDriveId?: string) { if (sharedDriveId) throw new Error("PILOT_MY_DRIVE_ONLY"); }
  async listPage(input: { rootId: string; pageToken?: string; signal: AbortSignal }): Promise<{ documents: readonly PilotPageDocument[]; nextPageToken?: string }> { if (input.rootId !== this.authorizedRootId) throw new Error("PILOT_ROOT_BINDING_VIOLATION"); if (!input.pageToken) { this.#descriptors.clear(); this.#content.clear(); } const page = await this.transportBinding.run(input.signal, () => this.client.listFiles({ rootId: this.authorizedRootId, pageToken: input.pageToken })); if (input.signal.aborted) throw new Error("PILOT_EXECUTION_TIMEOUT"); for (const descriptor of page.files) this.#descriptors.set(descriptor.fileId, descriptor); return { documents: page.files.map(file => ({ fileId: file.fileId, rootId: this.authorizedRootId, mimeType: file.mimeType, declaredBytes: file.size })), nextPageToken: page.nextPageToken }; }
  async download(input: { fileId: string; maximumBytes: number; signal: AbortSignal }): Promise<Uint8Array> { const descriptor = this.#descriptors.get(input.fileId); if (!descriptor || descriptor.corpusRootId !== this.authorizedRootId || descriptor.mimeType !== "application/pdf" || (descriptor.kind ?? "FILE") !== "FILE") throw new Error("PILOT_DOCUMENT_NOT_DOWNLOADABLE"); if (descriptor.size > input.maximumBytes) throw new Error("PILOT_PDF_LIMIT_EXCEEDED"); const bytes = await this.transportBinding.run(input.signal, () => this.client.readPdfContent(input.fileId)); if (input.signal.aborted) throw new Error("PILOT_EXECUTION_TIMEOUT"); if (bytes.byteLength > input.maximumBytes) throw new Error("PILOT_PDF_LIMIT_EXCEEDED"); this.#content.set(input.fileId, bytes); return bytes;
  }
  toCompletedSource(organizationId: string, connectionId: string): DocumentSource { const descriptors = [...this.#descriptors.values()].sort((a, b) => a.fileId.localeCompare(b.fileId)); const content = this.#content; return { sourceType: "GOOGLE_DRIVE", organizationId, sourceId: connectionId, async discover(): Promise<readonly DiscoveredDocument[]> { return descriptors.filter(file => !file.trashed && (file.kind ?? "FILE") !== "FOLDER").map(file => { const supported = file.mimeType === "application/pdf" && (file.kind ?? "FILE") === "FILE"; return { sourceDocumentId: file.fileId, displayName: file.displayName, mimeType: file.mimeType, size: file.size, modifiedAt: file.modifiedAt, supported, provenance: { sourceType: "GOOGLE_DRIVE", sourceId: connectionId, sourceDocumentId: file.fileId, locator: file.locator }, readContent: async () => { if (!supported) return new TextEncoder().encode(`UNSUPPORTED\0${file.fileId}\0${file.mimeType}`); const bytes = content.get(file.fileId); if (!bytes) throw new Error("PILOT_AUDITED_CONTENT_MISSING"); return bytes; } }; }); } }; }
}

export interface WiredPilotResult { readonly execution: Awaited<ReturnType<OneShotGoogleDrivePilotOrchestrator["execute"]>>; readonly report: IncrementalCorpusReport; readonly checkpointVersion: number }
export class WiredGoogleDrivePilotService {
  constructor(private readonly orchestrator: OneShotGoogleDrivePilotOrchestrator, private readonly driver: RealGoogleDrivePilotRuntimeDriver, private readonly processor: IncrementalCorpusProcessor, private readonly checkpoints: DurableCheckpointPort) {}
  async execute(config: PilotActivationConfiguration, invocation: OneShotPilotInvocation): Promise<WiredPilotResult> { const key = { organizationId: config.organizationId, sourceType: "GOOGLE_DRIVE" as const, sourceId: config.connectionId }; const prior = await this.checkpoints.load(key, config.connectionId); if (prior && (prior.checkpoint.organizationId !== key.organizationId || prior.checkpoint.sourceType !== key.sourceType || prior.checkpoint.sourceId !== key.sourceId)) throw new Error("CHECKPOINT_SOURCE_BOUNDARY_MISMATCH"); let completed: IncrementalCorpusRun | undefined; let checkpointVersion = prior?.version ?? 0; const execution = await this.orchestrator.execute(config, invocation, async ({ signal }) => { completed = await this.processor.process(this.driver.toCompletedSource(config.organizationId, config.connectionId), prior?.checkpoint); if (signal.aborted) throw new Error("PILOT_EXECUTION_TIMEOUT"); if (completed.report.failures.length) throw new Error("PILOT_PROCESSING_INCOMPLETE"); return async () => { await this.checkpoints.save(key, config.connectionId, completed!.checkpoint, prior?.version ?? null); checkpointVersion += 1; }; }); if (!completed) throw new Error("PILOT_PROCESSING_NOT_COMPLETED"); return { execution, report: completed.report, checkpointVersion }; }
}

export interface FixedCallbackIdentity { readonly organizationId: string; readonly operatorId: string; readonly connectionId: string; readonly callbackUrl: string }
export class FixedIdentityDurableCallbackAdapter {
  constructor(private readonly config: PilotActivationConfiguration, private readonly identity: FixedCallbackIdentity, private readonly runtime: DurableGoogleDriveCallbackRuntime) { if (config.organizationId !== identity.organizationId || config.connectionId !== identity.connectionId || config.exactCallbackUrl !== identity.callbackUrl) throw new Error("CALLBACK_FIXED_IDENTITY_MISMATCH"); }
  async handle(protocol: RuntimeCallbackInput): Promise<void> { await this.runtime.handle(this.config, protocol, this.identity); }
}

export interface RealPilotCompositionConfiguration { readonly activation: PilotActivationConfiguration; readonly operatorId: string; readonly callbackPath: string; readonly kmsResource: string; readonly secretManagerResource: string }
export function parseRealPilotCompositionConfiguration(source: ExternalActivationConfiguration & { OPERATOR_ID?: string; CALLBACK_PATH?: string; KMS_RESOURCE?: string }): RealPilotCompositionConfiguration { const activation = parsePilotActivationConfiguration(source); const operatorId = source.OPERATOR_ID?.trim(); const callbackPath = source.CALLBACK_PATH?.trim(); const kmsResource = source.KMS_RESOURCE?.trim(); if (!operatorId) throw new Error("PILOT_CONFIG_OPERATOR_ID_REQUIRED"); if (!callbackPath?.startsWith("/") || callbackPath.includes("?") || callbackPath.includes("#")) throw new Error("PILOT_CONFIG_CALLBACK_PATH_INVALID"); if (!kmsResource || !/^projects\/[^/]+\/locations\/[^/]+\/keyRings\/[^/]+\/cryptoKeys\/[^/]+\/cryptoKeyVersions\/[1-9]\d*$/.test(kmsResource)) throw new Error("PILOT_CONFIG_KMS_RESOURCE_INVALID"); if (!/^projects\/[a-z0-9-]+\/secrets\/[A-Za-z0-9_-]+\/versions\/[1-9]\d*$/.test(activation.googleClientSecretReference)) throw new Error("PILOT_CONFIG_SECRET_REFERENCE_INVALID"); return { activation, operatorId, callbackPath, kmsResource, secretManagerResource: activation.googleClientSecretReference }; }
export interface RealPilotComposition { readonly callbackHandler: (request: CallbackHttpRequest) => Promise<CallbackHttpResponse>; readonly pilot: WiredGoogleDrivePilotService }
export interface RealPilotCompositionDependencies { readonly configuration: RealPilotCompositionConfiguration; readonly callbackRuntime: DurableGoogleDriveCallbackRuntime; readonly driveConnection: DriveConnection; readonly driveCredentials: DriveCredentialProvider; readonly driveTransport: DeclaredGoogleDriveTransport; readonly lifecycle: ConnectionLifecycleRepository; readonly executions: PilotExecutionRepository; readonly audit: DownloadSecurityAuditSink | ((executionId: string) => DownloadSecurityAuditSink); readonly understandingProvider: DocumentUnderstandingProvider; readonly checkpoints: DurableCheckpointPort }
export function composeRealGoogleDrivePilot(input: RealPilotCompositionDependencies): RealPilotComposition { const activation = input.configuration.activation; if (input.driveConnection.organizationId !== activation.organizationId) throw new Error("PILOT_COMPOSITION_ORGANIZATION_MISMATCH"); if (input.driveConnection.connectionId !== activation.connectionId) throw new Error("PILOT_COMPOSITION_CONNECTION_MISMATCH"); if (input.driveConnection.authorizedRootId !== activation.authorizedRootId) throw new Error("PILOT_COMPOSITION_ROOT_MISMATCH"); const binding = new SingleAttemptSignalBindingTransport(input.driveTransport); const client = new RealGoogleDriveClient(input.driveConnection, input.driveCredentials, binding, activation.limits.maximumPdfBytes); const driver = new RealGoogleDrivePilotRuntimeDriver(client, binding, activation.authorizedRootId); const orchestrator = new OneShotGoogleDrivePilotOrchestrator(input.lifecycle, input.executions, input.audit, input.checkpoints, driver); const identity = { organizationId: activation.organizationId, operatorId: input.configuration.operatorId, connectionId: activation.connectionId, callbackUrl: activation.exactCallbackUrl }; const fixed = new FixedIdentityDurableCallbackAdapter(activation, identity, input.callbackRuntime); return { callbackHandler: createCloudRunCallbackHandler(input.configuration.callbackPath, fixed), pilot: new WiredGoogleDrivePilotService(orchestrator, driver, new IncrementalCorpusProcessor(input.understandingProvider), input.checkpoints) }; }
