import { createHash, randomBytes } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { DriveSourceFetchError } from "./google-drive-source-contract";
import type { SourceCheckpoint } from "./incremental-corpus-processor";
import { GoogleDriveTransportError, normalizeGoogleDriveError, type DriveCredentialProvider, type GoogleDriveOperation, type GoogleDriveTransport, type GoogleDriveTransportRequest, type PilotConnectionState } from "./real-google-drive-client";

export const GOOGLE_DRIVE_READONLY_SCOPE = "https://www.googleapis.com/auth/drive.readonly";
export interface PilotExecutionGate { readonly enabled: boolean }
export const DISABLED_GOOGLE_DRIVE_PILOT_GATE: PilotExecutionGate = Object.freeze({ enabled: false });
export function assertPilotEnabled(gate: PilotExecutionGate): void { if (gate.enabled !== true) throw new Error("GOOGLE_DRIVE_PILOT_NOT_CONFIGURED"); }
export async function runControlledPilot<T>(gate: PilotExecutionGate, execution: () => Promise<T>): Promise<T> { assertPilotEnabled(gate); return execution(); }

export interface FetchLikeResponse { readonly ok: boolean; readonly status: number; readonly headers: { get(name: string): string | null }; readonly body: ReadableStream<Uint8Array> | null }
export type FetchLike = (url: string, init: { readonly method: "GET"; readonly headers: Readonly<Record<string, string>>; readonly signal: AbortSignal }) => Promise<FetchLikeResponse>;
const API_ORIGIN = "https://www.googleapis.com";
const MAX_JSON_BYTES = 2 * 1024 * 1024;

async function readBounded(response: FetchLikeResponse, maximumBytes: number, controller: AbortController): Promise<Uint8Array> { if (!response.body) return new Uint8Array(); const reader = response.body.getReader(); const chunks: Uint8Array[] = []; let total = 0; try { while (true) { const item = await reader.read(); if (item.done) break; total += item.value.byteLength; if (total > maximumBytes) { controller.abort(); await reader.cancel(); throw new DriveSourceFetchError("DRIVE_DOCUMENT_TOO_LARGE", "TERMINAL"); } chunks.push(item.value); } } catch (error) { if (error instanceof DriveSourceFetchError) throw error; throw new GoogleDriveTransportError(undefined, [], "INTERRUPTED"); } const output = new Uint8Array(total); let offset = 0; for (const chunk of chunks) { output.set(chunk, offset); offset += chunk.length; } return output; }
const queryString = (parameters: GoogleDriveTransportRequest["parameters"]): string => { const query = new URLSearchParams(); for (const [key, value] of Object.entries(parameters)) if (value !== undefined) query.set(key, String(value)); return query.toString(); };

export class BoundedGoogleDriveHttpTransport implements GoogleDriveTransport {
  constructor(private readonly fetcher: FetchLike) {}
  async execute<T>(request: GoogleDriveTransportRequest): Promise<T> { const fileId = request.parameters.fileId === undefined ? undefined : encodeURIComponent(String(request.parameters.fileId)); const operation: Record<GoogleDriveOperation, { path: string; binary: boolean }> = { FILES_LIST: { path: "/drive/v3/files", binary: false }, FILES_GET: { path: `/drive/v3/files/${fileId}`, binary: false }, FILES_DOWNLOAD: { path: `/drive/v3/files/${fileId}`, binary: true }, CHANGES_START_TOKEN: { path: "/drive/v3/changes/startPageToken", binary: false }, CHANGES_LIST: { path: "/drive/v3/changes", binary: false } }; const route = operation[request.operation]; const controller = new AbortController(); let response: FetchLikeResponse; try { response = await this.fetcher(`${API_ORIGIN}${route.path}?${queryString(request.parameters)}`, { method: "GET", headers: { Authorization: `Bearer ${request.accessToken}`, Accept: route.binary ? "application/pdf" : "application/json" }, signal: controller.signal }); } catch { throw new GoogleDriveTransportError(undefined, [], "INTERRUPTED"); } if (!response.ok) { const bytes = await readBounded(response, MAX_JSON_BYTES, controller); let payload: { error?: { errors?: Array<{ reason?: string }> } } = {}; try { payload = JSON.parse(new TextDecoder().decode(bytes)) as typeof payload; } catch { /* sanitized empty error */ } const retryAfter = response.headers.get("retry-after"); throw new GoogleDriveTransportError(response.status, payload.error?.errors?.flatMap(({ reason }) => reason ? [reason] : []) ?? [], undefined, parseRetryAfter(retryAfter)); } const bytes = await readBounded(response, route.binary ? request.maximumResponseBytes ?? 0 : MAX_JSON_BYTES, controller); return (route.binary ? bytes : JSON.parse(new TextDecoder().decode(bytes))) as T; }
}

export function parseRetryAfter(value: string | null, nowMs = Date.now()): number | undefined { if (!value) return undefined; const seconds = Number(value); if (Number.isFinite(seconds) && seconds >= 0) return seconds * 1_000; const date = Date.parse(value); return Number.isFinite(date) && date > nowMs ? date - nowMs : undefined; }
export interface RetryPolicy { readonly maximumAttempts: number; readonly baseDelayMs: number; readonly maximumDelayMs: number }
export class RetryingGoogleDriveTransport implements GoogleDriveTransport { constructor(private readonly delegate: GoogleDriveTransport, private readonly policy: RetryPolicy, private readonly sleep: (ms: number) => Promise<void>, private readonly jitter: () => number) {} async execute<T>(request: GoogleDriveTransportRequest): Promise<T> { for (let attempt = 1; ; attempt++) try { return await this.delegate.execute<T>(request); } catch (error) { const normalized = normalizeGoogleDriveError(error); if (!normalized.retryable || attempt >= this.policy.maximumAttempts) throw error; const retryAfter = error instanceof GoogleDriveTransportError ? error.retryAfterMs : undefined; const exponential = Math.min(this.policy.maximumDelayMs, this.policy.baseDelayMs * 2 ** (attempt - 1)); await this.sleep(retryAfter ?? Math.min(this.policy.maximumDelayMs, exponential + Math.floor(this.jitter() * this.policy.baseDelayMs))); } } }

export interface OAuthPilotContext { readonly organizationId: string; readonly operatorId: string; readonly connectionId: string; readonly callbackUrl: string }
interface PendingOAuthState extends OAuthPilotContext { readonly nonce: string; readonly expiresAt: number; readonly consumed: boolean }
export class GoogleDriveOAuthBoundary { readonly #states = new Map<string, PendingOAuthState>(); constructor(private readonly clientId: string, private readonly exactCallbackUrl: string, private readonly now: () => number = Date.now) {} createAuthorizationRequest(context: OAuthPilotContext): { readonly authorizationUrl: string; readonly state: string; readonly nonce: string } { if (context.callbackUrl !== this.exactCallbackUrl) throw new Error("GOOGLE_OAUTH_CALLBACK_REJECTED"); const state = randomBytes(32).toString("base64url"); const nonce = randomBytes(32).toString("base64url"); this.#states.set(state, { ...context, nonce, expiresAt: this.now() + 10 * 60_000, consumed: false }); const url = new URL("https://accounts.google.com/o/oauth2/v2/auth"); url.search = new URLSearchParams({ client_id: this.clientId, redirect_uri: this.exactCallbackUrl, response_type: "code", access_type: "offline", prompt: "consent", scope: GOOGLE_DRIVE_READONLY_SCOPE, state, nonce }).toString(); return { authorizationUrl: url.toString(), state, nonce }; } validateCallback(input: OAuthPilotContext & { readonly state: string; readonly nonce: string; readonly grantedScopes: readonly string[] }): void { const pending = this.#states.get(input.state); if (!pending || pending.consumed) throw new Error("GOOGLE_OAUTH_STATE_REPLAY_OR_UNKNOWN"); if (pending.expiresAt <= this.now()) throw new Error("GOOGLE_OAUTH_STATE_EXPIRED"); if (pending.nonce !== input.nonce) throw new Error("GOOGLE_OAUTH_NONCE_MISMATCH"); if (input.callbackUrl !== this.exactCallbackUrl || pending.callbackUrl !== input.callbackUrl) throw new Error("GOOGLE_OAUTH_CALLBACK_REJECTED"); if (pending.organizationId !== input.organizationId) throw new Error("GOOGLE_OAUTH_ORGANIZATION_MISMATCH"); if (pending.operatorId !== input.operatorId) throw new Error("GOOGLE_OAUTH_OPERATOR_MISMATCH"); if (pending.connectionId !== input.connectionId) throw new Error("GOOGLE_OAUTH_CONNECTION_MISMATCH"); if (!input.grantedScopes.includes(GOOGLE_DRIVE_READONLY_SCOPE) || input.grantedScopes.some((scope) => scope !== GOOGLE_DRIVE_READONLY_SCOPE)) throw new Error("GOOGLE_OAUTH_SCOPE_MISMATCH"); this.#states.set(input.state, { ...pending, consumed: true }); } }

export interface AuthenticatedEncryptionPort { seal(plaintext: Uint8Array, context: { organizationId: string; connectionId: string }): Promise<Uint8Array>; open(ciphertext: Uint8Array, context: { organizationId: string; connectionId: string }): Promise<Uint8Array> }
export interface RefreshCredentialVault { store(input: { organizationId: string; connectionId: string; refreshToken: string }): Promise<void>; load(organizationId: string, connectionId: string): Promise<string>; destroy(organizationId: string, connectionId: string): Promise<void> }
export class EncryptedRefreshCredentialVault implements RefreshCredentialVault { readonly #records = new Map<string, Uint8Array>(); constructor(private readonly encryption: AuthenticatedEncryptionPort) {} #key(org: string, connection: string): string { return `${org}\0${connection}`; } async store(input: { organizationId: string; connectionId: string; refreshToken: string }): Promise<void> { this.#records.set(this.#key(input.organizationId, input.connectionId), await this.encryption.seal(new TextEncoder().encode(input.refreshToken), input)); } async load(organizationId: string, connectionId: string): Promise<string> { const value = this.#records.get(this.#key(organizationId, connectionId)); if (!value) throw new Error("GOOGLE_CREDENTIAL_UNAVAILABLE"); return new TextDecoder().decode(await this.encryption.open(value, { organizationId, connectionId })); } async destroy(organizationId: string, connectionId: string): Promise<void> { this.#records.delete(this.#key(organizationId, connectionId)); } }
export class DisabledDriveCredentialProvider implements DriveCredentialProvider { async getValidAccessToken(connectionId: string): Promise<{ value: string }> { void connectionId; throw new Error("GOOGLE_DRIVE_PILOT_NOT_CONFIGURED"); } }
export function connectionStateForFailure(error: unknown): PilotConnectionState { if (error instanceof DriveSourceFetchError && error.kind === "AUTHORIZATION") return error.code.includes("REVOK") ? "REVOKED" : "REAUTHORIZATION_REQUIRED"; return "CONNECTED"; }

export interface PilotConnectionRecord { readonly organizationId: string; readonly connectionId: string; readonly googleSubject: string; readonly authorizedRootId: string; readonly authorizationState: PilotConnectionState; readonly grantedScopeState: "VALID" | "INVALID" }
export class LocalPilotConnectionStore { constructor(private readonly directory: string) {} #path(org: string, connection: string): string { return join(this.directory, `${createHash("sha256").update(`${org}\0${connection}`).digest("hex")}.connection.json`); } async load(org: string, connection: string): Promise<PilotConnectionRecord | null> { try { const record = JSON.parse(await readFile(this.#path(org, connection), "utf8")) as PilotConnectionRecord; return record.organizationId === org && record.connectionId === connection ? record : null; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return null; throw error; } } async save(record: PilotConnectionRecord): Promise<void> { await mkdir(this.directory, { recursive: true, mode: 0o700 }); const target = this.#path(record.organizationId, record.connectionId); const temporary = `${target}.tmp`; await writeFile(temporary, `${JSON.stringify(record)}\n`, { mode: 0o600 }); await rename(temporary, target); } }

export interface DownloadSecurityEvent { readonly organizationId: string; readonly connectionId: string; readonly documentReference: string; readonly timestamp: string; readonly rootProof: "PASSED"; readonly outcome: "STARTED" | "SUCCEEDED" | "FAILED" }
export interface DownloadSecurityAuditSink { append(event: DownloadSecurityEvent): Promise<void> }
export interface DownloadSafetyLimits { readonly expectedCorpusSize: number; readonly hardMaximumDownloads: number; readonly maximumExpansionRatio: number; readonly maximumBoundaryFailures: number }
export class PilotDownloadSecurityMonitor { #downloads = 0; #boundaryFailures = 0; constructor(private readonly organizationId: string, private readonly connectionId: string, private readonly limits: DownloadSafetyLimits, private readonly audit: DownloadSecurityAuditSink, private readonly now: () => Date = () => new Date()) {} async beforeDownload(fileId: string): Promise<string> { const next = this.#downloads + 1; if (next > this.limits.hardMaximumDownloads || next > Math.ceil(this.limits.expectedCorpusSize * this.limits.maximumExpansionRatio)) throw new DriveSourceFetchError("DRIVE_DOWNLOAD_ANOMALY_STOP", "TERMINAL"); this.#downloads = next; const documentReference = createHash("sha256").update(`${this.connectionId}\0${fileId}`).digest("hex"); await this.audit.append({ organizationId: this.organizationId, connectionId: this.connectionId, documentReference, timestamp: this.now().toISOString(), rootProof: "PASSED", outcome: "STARTED" }); return documentReference; } async afterDownload(documentReference: string, outcome: "SUCCEEDED" | "FAILED"): Promise<void> { await this.audit.append({ organizationId: this.organizationId, connectionId: this.connectionId, documentReference, timestamp: this.now().toISOString(), rootProof: "PASSED", outcome }); } recordBoundaryFailure(): void { this.#boundaryFailures += 1; if (this.#boundaryFailures > this.limits.maximumBoundaryFailures) throw new DriveSourceFetchError("DRIVE_BOUNDARY_ANOMALY_STOP", "TERMINAL"); } }
export class AuditedGoogleDriveTransport implements GoogleDriveTransport { constructor(private readonly delegate: GoogleDriveTransport, private readonly monitor: PilotDownloadSecurityMonitor) {} async execute<T>(request: GoogleDriveTransportRequest): Promise<T> { if (request.operation !== "FILES_DOWNLOAD") return this.delegate.execute<T>(request); const reference = await this.monitor.beforeDownload(String(request.parameters.fileId)); try { const result = await this.delegate.execute<T>(request); await this.monitor.afterDownload(reference, "SUCCEEDED"); return result; } catch (error) { await this.monitor.afterDownload(reference, "FAILED"); throw error; } } }

export interface PersistentPilotRecord { readonly version: number; readonly organizationId: string; readonly connectionId: string; readonly checkpoint: SourceCheckpoint }
export class LocalPersistentPilotCheckpointStore { constructor(private readonly directory: string) {} #path(org: string, connection: string): string { return join(this.directory, `${createHash("sha256").update(`${org}\0${connection}`).digest("hex")}.json`); } async load(org: string, connection: string): Promise<PersistentPilotRecord | null> { try { return JSON.parse(await readFile(this.#path(org, connection), "utf8")) as PersistentPilotRecord; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return null; throw error; } } async saveAtomically(org: string, connection: string, checkpoint: SourceCheckpoint, expectedVersion: number | null): Promise<PersistentPilotRecord> { if (checkpoint.organizationId !== org || checkpoint.sourceId !== connection) throw new Error("CHECKPOINT_SOURCE_BOUNDARY_MISMATCH"); const current = await this.load(org, connection); if ((current?.version ?? null) !== expectedVersion) throw new Error("CHECKPOINT_OPTIMISTIC_LOCK_CONFLICT"); const record = { version: (current?.version ?? 0) + 1, organizationId: org, connectionId: connection, checkpoint }; await mkdir(this.directory, { recursive: true, mode: 0o700 }); const target = this.#path(org, connection); const temporary = `${target}.tmp`; await writeFile(temporary, `${JSON.stringify(record)}\n`, { mode: 0o600 }); await rename(temporary, target); return record; } }

export interface SyntheticPilotConfiguration { readonly organizationId: "synthetic-pilot"; readonly connectionId: "synthetic-drive-pilot"; readonly expectedRecords: 40; readonly requiredScope: typeof GOOGLE_DRIVE_READONLY_SCOPE; readonly maximumDocumentBytes: number; readonly authorizationState: PilotConnectionState; readonly killSwitchEnabled: false }
export const SYNTHETIC_GOOGLE_DRIVE_PILOT: SyntheticPilotConfiguration = Object.freeze({ organizationId: "synthetic-pilot", connectionId: "synthetic-drive-pilot", expectedRecords: 40, requiredScope: GOOGLE_DRIVE_READONLY_SCOPE, maximumDocumentBytes: 25 * 1024 * 1024, authorizationState: "DISCONNECTED", killSwitchEnabled: false });
