import { GoogleOAuthFailure, type GoogleOAuthClientPort, type GoogleOAuthTokenSet, type ManagedEncryptionProvider } from "./google-drive-activation";

export interface SecretManagerClientPort { accessSecretVersion(resourceName: string): Promise<Uint8Array | null> }
export class GoogleSecretManagerAdapter {
  constructor(private readonly client: SecretManagerClientPort) {}
  async resolve(reference: string): Promise<string> { if (!/^projects\/[a-z0-9-]+\/secrets\/[A-Za-z0-9_-]+\/versions\/(?:[1-9]\d*|latest)$/.test(reference)) throw new Error("SECRET_REFERENCE_INVALID"); try { const value = await this.client.accessSecretVersion(reference); if (!value?.byteLength) throw new Error("missing"); return new TextDecoder().decode(value); } catch { throw new Error("SECRET_MANAGER_UNAVAILABLE"); } }
}

export interface CloudKmsClientPort { encrypt(input: { keyResource: string; plaintext: Uint8Array; additionalAuthenticatedData: Uint8Array }): Promise<Uint8Array>; decrypt(input: { keyResource: string; ciphertext: Uint8Array; additionalAuthenticatedData: Uint8Array }): Promise<Uint8Array> }
export class GoogleCloudKmsManagedEncryptionProvider implements ManagedEncryptionProvider {
  constructor(private readonly client: CloudKmsClientPort, private readonly configuredKeyResource: string) {}
  #resource(keyId: string, keyVersion: string): string { const expected = `${keyId}/cryptoKeyVersions/${keyVersion}`; if (expected !== this.configuredKeyResource || !/^projects\/[^/]+\/locations\/[^/]+\/keyRings\/[^/]+\/cryptoKeys\/[^/]+\/cryptoKeyVersions\/[1-9]\d*$/.test(expected)) throw new Error("KMS_KEY_REFERENCE_INVALID"); return expected; }
  #aad(context: Readonly<Record<string, string>>): Uint8Array { if (!context.organizationId || !context.connectionId) throw new Error("KMS_CONTEXT_INVALID"); return new TextEncoder().encode(JSON.stringify({ organizationId: context.organizationId, connectionId: context.connectionId })); }
  async encrypt(input: { plaintext: Uint8Array; keyId: string; keyVersion: string; authenticatedContext: Readonly<Record<string, string>> }): Promise<Uint8Array> { try { return await this.client.encrypt({ keyResource: this.#resource(input.keyId, input.keyVersion), plaintext: input.plaintext, additionalAuthenticatedData: this.#aad(input.authenticatedContext) }); } catch { throw new Error("CLOUD_KMS_ENCRYPTION_FAILED"); } }
  async decrypt(input: { ciphertext: Uint8Array; keyId: string; keyVersion: string; authenticatedContext: Readonly<Record<string, string>> }): Promise<Uint8Array> { try { return await this.client.decrypt({ keyResource: this.#resource(input.keyId, input.keyVersion), ciphertext: input.ciphertext, additionalAuthenticatedData: this.#aad(input.authenticatedContext) }); } catch { throw new Error("CLOUD_KMS_DECRYPTION_FAILED"); } }
}

export interface OAuthHttpResponse { readonly status: number; readonly body: ReadableStream<Uint8Array> | null }
export type OAuthHttpFetch = (url: string, init: { method: "POST"; headers: Readonly<Record<string, string>>; body: string; signal: AbortSignal }) => Promise<OAuthHttpResponse>;
const TOKEN_ENDPOINT = "https://oauth2.googleapis.com/token";
const REVOKE_ENDPOINT = "https://oauth2.googleapis.com/revoke";
export const GOOGLE_OAUTH_MAX_EXPIRES_IN_SECONDS = 24 * 60 * 60;
async function boundedJson(response: OAuthHttpResponse, maximumBytes: number, controller: AbortController): Promise<Record<string, unknown>> { if (!response.body) throw new Error("GOOGLE_OAUTH_RESPONSE_INVALID"); const reader = response.body.getReader(); const chunks: Uint8Array[] = []; let size = 0; while (true) { const item = await reader.read(); if (item.done) break; size += item.value.byteLength; if (size > maximumBytes) { controller.abort(); await reader.cancel(); throw new Error("GOOGLE_OAUTH_RESPONSE_TOO_LARGE"); } chunks.push(item.value); } const bytes = new Uint8Array(size); let offset = 0; for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; } try { return JSON.parse(new TextDecoder().decode(bytes)) as Record<string, unknown>; } catch { throw new Error("GOOGLE_OAUTH_RESPONSE_INVALID"); } }
export class GoogleOAuthHttpAdapter implements GoogleOAuthClientPort {
  constructor(private readonly clientId: string, private readonly callbackUrl: string, private readonly secretReference: string, private readonly secrets: GoogleSecretManagerAdapter, private readonly fetcher: OAuthHttpFetch, private readonly timeoutMs = 10_000, private readonly maximumResponseBytes = 64 * 1024) {}
  async #post(url: typeof TOKEN_ENDPOINT | typeof REVOKE_ENDPOINT, parameters: Readonly<Record<string, string>>): Promise<Record<string, unknown>> { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), this.timeoutMs); try { const response = await this.fetcher(url, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded", Accept: "application/json" }, body: new URLSearchParams(parameters).toString(), signal: controller.signal }); const payload = await boundedJson(response, this.maximumResponseBytes, controller); if (response.status < 200 || response.status >= 300) { if (payload.error === "invalid_grant") throw new GoogleOAuthFailure("invalid_grant"); throw new GoogleOAuthFailure(response.status === 429 || response.status >= 500 ? "refresh_failed" : "exchange_failed"); } return payload; } catch (error) { if (error instanceof GoogleOAuthFailure || (error instanceof Error && error.message.startsWith("GOOGLE_OAUTH_RESPONSE_"))) throw error; throw new GoogleOAuthFailure("refresh_failed"); } finally { clearTimeout(timeout); } }
  #tokens(payload: Record<string, unknown>, requireRefresh: boolean): GoogleOAuthTokenSet { if (typeof payload.access_token !== "string" || typeof payload.expires_in !== "number" || !Number.isInteger(payload.expires_in) || !Number.isFinite(payload.expires_in) || payload.expires_in <= 0 || payload.expires_in > GOOGLE_OAUTH_MAX_EXPIRES_IN_SECONDS || typeof payload.scope !== "string" || (requireRefresh && typeof payload.refresh_token !== "string")) throw new Error("GOOGLE_OAUTH_RESPONSE_INVALID"); return { accessToken: payload.access_token, expiresInSeconds: payload.expires_in, ...(typeof payload.refresh_token === "string" ? { refreshToken: payload.refresh_token } : {}), grantedScopes: payload.scope.split(" ").filter(Boolean), subject: "provider-subject-unavailable" }; }
  async exchangeAuthorizationCode(input: { code: string; callbackUrl: string }): Promise<GoogleOAuthTokenSet> { if (input.callbackUrl !== this.callbackUrl) throw new Error("GOOGLE_OAUTH_CALLBACK_REJECTED"); const clientSecret = await this.secrets.resolve(this.secretReference); const payload = await this.#post(TOKEN_ENDPOINT, { code: input.code, client_id: this.clientId, client_secret: clientSecret, redirect_uri: this.callbackUrl, grant_type: "authorization_code" }); return this.#tokens(payload, true); }
  async refreshAccessToken(refreshToken: string): Promise<Omit<GoogleOAuthTokenSet, "refreshToken" | "subject">> { const clientSecret = await this.secrets.resolve(this.secretReference); const tokens = this.#tokens(await this.#post(TOKEN_ENDPOINT, { client_id: this.clientId, client_secret: clientSecret, refresh_token: refreshToken, grant_type: "refresh_token" }), false); return { accessToken: tokens.accessToken, expiresInSeconds: tokens.expiresInSeconds, grantedScopes: tokens.grantedScopes }; }
  async revokeCredential(credential: string): Promise<void> { await this.#post(REVOKE_ENDPOINT, { token: credential }); }
}

export interface CallbackHttpRequest { readonly method: string; readonly path: string; readonly query: Readonly<Record<string, string | readonly string[] | undefined>>; readonly headers?: Readonly<Record<string, string | undefined>>; readonly cookies?: Readonly<Record<string, string | undefined>> }
export interface CallbackHttpResponse { readonly status: number; readonly headers: Readonly<Record<string, string>>; readonly body: string }
export interface CallbackRuntimePort { handle(input: { state: string; code?: string; oauthError?: string }): Promise<void> }
export function createCloudRunCallbackHandler(exactPath: string, runtime: CallbackRuntimePort): (request: CallbackHttpRequest) => Promise<CallbackHttpResponse> { return async request => { if (request.method !== "GET" || request.path !== exactPath) return { status: 404, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" }, body: JSON.stringify({ status: "NOT_FOUND" }) }; const keys = Object.keys(request.query); const allowed = new Set(["state", "code", "error"]); const { state, code, error } = request.query; if (keys.some(key => !allowed.has(key)) || typeof state !== "string" || ((typeof code === "string") === (typeof error === "string")) || (code !== undefined && typeof code !== "string") || (error !== undefined && typeof error !== "string")) return { status: 400, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" }, body: JSON.stringify({ status: "INVALID_CALLBACK" }) }; try { await runtime.handle({ state, ...(typeof code === "string" ? { code } : {}), ...(typeof error === "string" ? { oauthError: error } : {}) }); return { status: 200, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" }, body: JSON.stringify({ status: "CONNECTED" }) }; } catch { return { status: 400, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" }, body: JSON.stringify({ status: "CALLBACK_REJECTED" }) }; } }; }
