import { Prisma, PrismaClient } from "@prisma/client";
import type { SourceCheckpointKey } from "./source-checkpoint-store";
import type { ConnectionLifecycleRecord, ConnectionLifecycleRepository, CredentialEnvelopeRecord, CredentialEnvelopeRepository, DurableDriveAuditEvent, DurableDriveAuditRepository } from "./google-drive-activation";
import type { DurableCheckpointPort, DurableOAuthStateRecord, DurableOAuthStateRepository, PilotExecutionRecord, PilotExecutionRepository } from "./google-drive-durable-runtime";
import type { SourceCheckpoint } from "./incremental-corpus-processor";

export class PrismaDriveOAuthStateRepository implements DurableOAuthStateRepository {
  constructor(private readonly client: PrismaClient) {}
  async create(record: DurableOAuthStateRecord): Promise<void> { await this.client.driveOAuthState.create({ data: { ...record, nonceHash: record.stateHash, createdAt: new Date(record.createdAt), expiresAt: new Date(record.expiresAt), consumedAt: record.consumedAt ? new Date(record.consumedAt) : null } }); }
  async consume(input: { stateHash: string; now: string }): Promise<DurableOAuthStateRecord | null> {
    const now = new Date(input.now);
    const result = await this.client.driveOAuthState.updateMany({ where: { stateHash: input.stateHash, consumedAt: null, expiresAt: { gt: now } }, data: { consumedAt: now } });
    if (result.count !== 1) return null;
    const record = await this.client.driveOAuthState.findUniqueOrThrow({ where: { stateHash: input.stateHash } });
    return { stateHash: record.stateHash, organizationId: record.organizationId, operatorId: record.operatorId, connectionId: record.connectionId, callbackUrl: record.callbackUrl, createdAt: record.createdAt.toISOString(), expiresAt: record.expiresAt.toISOString(), consumedAt: record.consumedAt?.toISOString(), schemaVersion: 1 };
  }
}

export class PrismaDriveConnectionLifecycleRepository implements ConnectionLifecycleRepository { constructor(private readonly client: PrismaClient) {} async load(organizationId: string, connectionId: string): Promise<ConnectionLifecycleRecord | null> { return this.client.driveConnectionState.findUnique({ where: { organizationId_connectionId: { organizationId, connectionId } } }); } async transition(input: { organizationId: string; connectionId: string; from: readonly ConnectionLifecycleRecord["state"][]; to: ConnectionLifecycleRecord["state"] }): Promise<ConnectionLifecycleRecord> { const updated = await this.client.driveConnectionState.updateMany({ where: { organizationId: input.organizationId, connectionId: input.connectionId, state: { in: [...input.from] } }, data: { state: input.to, revision: { increment: 1 } } }); if (updated.count !== 1) throw new Error("CONNECTION_LIFECYCLE_CONFLICT"); return this.client.driveConnectionState.findUniqueOrThrow({ where: { organizationId_connectionId: { organizationId: input.organizationId, connectionId: input.connectionId } } }); } }

export class PrismaDriveCredentialEnvelopeRepository implements CredentialEnvelopeRepository { constructor(private readonly client: PrismaClient) {} async load(organizationId: string, connectionId: string): Promise<CredentialEnvelopeRecord | null> { const row = await this.client.driveCredentialEnvelope.findUnique({ where: { organizationId_connectionId: { organizationId, connectionId } } }); return row ? { ...row, encryptedRefreshCredential: new Uint8Array(row.encryptedRefreshCredential), createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() } : null; } async save(record: Omit<CredentialEnvelopeRecord, "revision">, expectedRevision: number | null): Promise<CredentialEnvelopeRecord> { if (expectedRevision === null) { try { await this.client.driveCredentialEnvelope.create({ data: { ...record, grantedScopes: [...record.grantedScopes], encryptedRefreshCredential: Buffer.from(record.encryptedRefreshCredential), createdAt: new Date(record.createdAt), updatedAt: new Date(record.updatedAt) } }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") throw new Error("CREDENTIAL_OPTIMISTIC_LOCK_CONFLICT"); throw error; } } else { const result = await this.client.driveCredentialEnvelope.updateMany({ where: { organizationId: record.organizationId, connectionId: record.connectionId, revision: expectedRevision }, data: { encryptedRefreshCredential: Buffer.from(record.encryptedRefreshCredential), keyId: record.keyId, keyVersion: record.keyVersion, grantedScopes: [...record.grantedScopes], providerSubject: record.providerSubject, revision: { increment: 1 }, updatedAt: new Date(record.updatedAt) } }); if (result.count !== 1) throw new Error("CREDENTIAL_OPTIMISTIC_LOCK_CONFLICT"); } return (await this.load(record.organizationId, record.connectionId))!; } async destroy(organizationId: string, connectionId: string): Promise<void> { await this.client.driveCredentialEnvelope.deleteMany({ where: { organizationId, connectionId } }); } }

export class PrismaDriveAuditRepository implements DurableDriveAuditRepository { constructor(private readonly client: PrismaClient) {} async appendOnly(event: DurableDriveAuditEvent): Promise<void> { await this.client.driveSecurityAuditEvent.create({ data: { organizationId: event.organizationId, connectionId: event.connectionId, executionId: event.executionId, documentReference: event.documentReference, eventType: event.eventType, operation: event.operation, outcome: event.outcome, failureClassification: event.failureClassification, rootProof: event.rootProof, occurredAt: new Date(event.timestamp) } }); } }

export class PrismaDriveCheckpointRepository implements DurableCheckpointPort { constructor(private readonly client: PrismaClient) {} async available(): Promise<boolean> { return true; } async load(key: SourceCheckpointKey, connectionId: string): Promise<{ version: number; checkpoint: SourceCheckpoint } | null> { const row = await this.client.driveSourceCheckpoint.findUnique({ where: { organizationId_sourceType_sourceId_connectionId: { organizationId: key.organizationId, sourceType: key.sourceType, sourceId: key.sourceId, connectionId } } }); return row ? { version: row.version, checkpoint: row.checkpoint as unknown as SourceCheckpoint } : null; } async save(key: SourceCheckpointKey, connectionId: string, checkpoint: SourceCheckpoint, expectedVersion: number | null): Promise<void> { if (checkpoint.organizationId !== key.organizationId || checkpoint.sourceType !== key.sourceType || checkpoint.sourceId !== key.sourceId || connectionId !== key.sourceId) throw new Error("CHECKPOINT_SOURCE_BOUNDARY_MISMATCH"); const identity = { organizationId: key.organizationId, sourceType: key.sourceType, sourceId: key.sourceId, connectionId }; const data = { processingVersion: checkpoint.entries[0]?.processingVersion ?? "empty", checkpoint: checkpoint as unknown as Prisma.InputJsonValue }; if (expectedVersion === null) { try { await this.client.driveSourceCheckpoint.create({ data: { ...identity, ...data } }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") throw new Error("CHECKPOINT_OPTIMISTIC_LOCK_CONFLICT"); throw error; } } else { const result = await this.client.driveSourceCheckpoint.updateMany({ where: { ...identity, version: expectedVersion }, data: { ...data, version: { increment: 1 } } }); if (result.count !== 1) throw new Error("CHECKPOINT_OPTIMISTIC_LOCK_CONFLICT"); } } }

export class PrismaDrivePilotExecutionRepository implements PilotExecutionRepository { constructor(private readonly client: PrismaClient) {} async begin(record: PilotExecutionRecord): Promise<void> { try { await this.client.drivePilotExecution.create({ data: { id: record.id, organizationId: record.organizationId, connectionId: record.connectionId, authorizedRootId: record.authorizedRootId, status: "RUNNING", configurationVersion: record.configurationVersion, startedAt: record.startedAt ? new Date(record.startedAt) : new Date(), discoveredCount: record.discoveredCount, downloadedCount: record.downloadedCount, pageCount: record.pageCount } }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") throw new Error("PILOT_EXECUTION_ALREADY_ACTIVE"); throw error; } } async finish(id: string, update: Pick<PilotExecutionRecord, "status" | "completedAt" | "failureClassification" | "discoveredCount" | "downloadedCount" | "pageCount">): Promise<void> { const result = await this.client.drivePilotExecution.updateMany({ where: { id, status: "RUNNING" }, data: { status: update.status, completedAt: update.completedAt ? new Date(update.completedAt) : null, failureClassification: update.failureClassification, discoveredCount: update.discoveredCount, downloadedCount: update.downloadedCount, pageCount: update.pageCount } }); if (result.count !== 1) throw new Error("PILOT_EXECUTION_STATE_CONFLICT"); } }
