import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { DriveSourceFetchError } from "./google-drive-source-contract";
import { AuditedGoogleDriveTransport, BoundedGoogleDriveHttpTransport, DISABLED_GOOGLE_DRIVE_PILOT_GATE, DisabledDriveCredentialProvider, EncryptedRefreshCredentialVault, GOOGLE_DRIVE_READONLY_SCOPE, GoogleDriveOAuthBoundary, LocalPersistentPilotCheckpointStore, LocalPilotConnectionStore, PilotDownloadSecurityMonitor, RetryingGoogleDriveTransport, SYNTHETIC_GOOGLE_DRIVE_PILOT, assertPilotEnabled, connectionStateForFailure, parseRetryAfter, runControlledPilot, type AuthenticatedEncryptionPort, type DownloadSecurityEvent, type FetchLikeResponse, type PilotExecutionGate } from "./google-drive-pilot-infrastructure";
import { GoogleDriveTransportError, type GoogleDriveTransport, type GoogleDriveTransportRequest } from "./real-google-drive-client";

const response = (chunks: Uint8Array[], status = 200, headers: Record<string, string> = {}): FetchLikeResponse => ({ ok: status >= 200 && status < 300, status, headers: { get: (name) => headers[name.toLowerCase()] ?? null }, body: new ReadableStream({ start(controller) { for (const chunk of chunks) controller.enqueue(chunk); controller.close(); } }) });
const request: GoogleDriveTransportRequest = { operation: "FILES_DOWNLOAD", accessToken: "sentinel", parameters: { fileId: "file", alt: "media" }, maximumResponseBytes: 25 * 1024 * 1024 };

describe("controlled Drive pilot infrastructure", () => {
  it("streams within the limit and aborts oversized bodies before unbounded buffering", async () => { let signal: AbortSignal | undefined; const good = new BoundedGoogleDriveHttpTransport(async (_url, init) => { signal = init.signal; return response([new Uint8Array(1024), new Uint8Array(1024)]); }); expect((await good.execute<Uint8Array>({ ...request, maximumResponseBytes: 2048 })).byteLength).toBe(2048); expect(signal?.aborted).toBe(false); let chunksRead = 0; const chunk = new Uint8Array(1024 * 1024); const oversized = new BoundedGoogleDriveHttpTransport(async (_url, init) => { signal = init.signal; return { ...response([]), body: new ReadableStream({ pull(controller) { chunksRead += 1; controller.enqueue(chunk); if (chunksRead > 30) controller.close(); } }) }; }); await expect(oversized.execute({ ...request, maximumResponseBytes: 25 * 1024 * 1024 })).rejects.toMatchObject({ code: "DRIVE_DOCUMENT_TOO_LARGE" }); expect(signal?.aborted).toBe(true); expect(chunksRead).toBeLessThanOrEqual(27); });
  it("maps HTTP errors without leaking response bodies", async () => { const transport = new BoundedGoogleDriveHttpTransport(async () => response([new TextEncoder().encode(JSON.stringify({ error: { errors: [{ reason: "quotaExceeded" }] } }))], 403, { "retry-after": "3" })); await expect(transport.execute(request)).rejects.toMatchObject({ status: 403, reasons: ["quotaExceeded"], retryAfterMs: 3000 }); });
  it("validates OAuth state, nonce, binding, callback, expiry, replay, and exact scope", () => { let now = 1_000; const oauth = new GoogleDriveOAuthBoundary("client-id-placeholder", "https://pilot.example.test/oauth/callback", () => now); const context = { organizationId: "org", operatorId: "operator", connectionId: "connection", callbackUrl: "https://pilot.example.test/oauth/callback" }; const valid = oauth.createAuthorizationRequest(context); expect(valid.authorizationUrl).toContain(encodeURIComponent(GOOGLE_DRIVE_READONLY_SCOPE)); oauth.validateCallback({ ...context, state: valid.state, nonce: valid.nonce, grantedScopes: [GOOGLE_DRIVE_READONLY_SCOPE] }); expect(() => oauth.validateCallback({ ...context, state: valid.state, nonce: valid.nonce, grantedScopes: [GOOGLE_DRIVE_READONLY_SCOPE] })).toThrow("GOOGLE_OAUTH_STATE_REPLAY_OR_UNKNOWN"); const attacks = [{ organizationId: "other" }, { operatorId: "other" }, { connectionId: "other" }, { callbackUrl: "https://evil.test/callback" }]; for (const attack of attacks) { const item = oauth.createAuthorizationRequest(context); expect(() => oauth.validateCallback({ ...context, ...attack, state: item.state, nonce: item.nonce, grantedScopes: [GOOGLE_DRIVE_READONLY_SCOPE] })).toThrow(); } const wrongNonce = oauth.createAuthorizationRequest(context); expect(() => oauth.validateCallback({ ...context, state: wrongNonce.state, nonce: "wrong", grantedScopes: [GOOGLE_DRIVE_READONLY_SCOPE] })).toThrow("GOOGLE_OAUTH_NONCE_MISMATCH"); for (const scopes of [[], ["other"], [GOOGLE_DRIVE_READONLY_SCOPE, "other"]]) { const item = oauth.createAuthorizationRequest(context); expect(() => oauth.validateCallback({ ...context, state: item.state, nonce: item.nonce, grantedScopes: scopes })).toThrow("GOOGLE_OAUTH_SCOPE_MISMATCH"); } const expired = oauth.createAuthorizationRequest(context); now += 11 * 60_000; expect(() => oauth.validateCallback({ ...context, state: expired.state, nonce: expired.nonce, grantedScopes: [GOOGLE_DRIVE_READONLY_SCOPE] })).toThrow("GOOGLE_OAUTH_STATE_EXPIRED"); expect(() => oauth.createAuthorizationRequest({ ...context, callbackUrl: "https://evil.test" })).toThrow("GOOGLE_OAUTH_CALLBACK_REJECTED"); });
  it("keeps refresh credentials encrypted and tenant-bound while access credentials remain disabled", async () => { const encryption: AuthenticatedEncryptionPort = { async seal(value, context) { return new TextEncoder().encode(`${context.organizationId}:${context.connectionId}:${Buffer.from(value).toString("base64")}`); }, async open(value, context) { const prefix = `${context.organizationId}:${context.connectionId}:`; const encoded = new TextDecoder().decode(value); if (!encoded.startsWith(prefix)) throw new Error("AAD_MISMATCH"); return new Uint8Array(Buffer.from(encoded.slice(prefix.length), "base64")); } }; const vault = new EncryptedRefreshCredentialVault(encryption); await vault.store({ organizationId: "org", connectionId: "connection", refreshToken: "refresh-secret" }); await expect(vault.load("org", "connection")).resolves.toBe("refresh-secret"); await expect(vault.load("other", "connection")).rejects.toThrow("GOOGLE_CREDENTIAL_UNAVAILABLE"); await vault.destroy("org", "connection"); await expect(vault.load("org", "connection")).rejects.toThrow("GOOGLE_CREDENTIAL_UNAVAILABLE"); await expect(new DisabledDriveCredentialProvider().getValidAccessToken("connection")).rejects.toThrow("GOOGLE_DRIVE_PILOT_NOT_CONFIGURED"); });
  it("retries only bounded retryable failures with Retry-After and deterministic jitter", async () => { let calls = 0; const waits: number[] = []; const delegate: GoogleDriveTransport = { async execute<T>() { calls += 1; if (calls < 3) throw new GoogleDriveTransportError(429, ["rateLimitExceeded"], undefined, calls === 1 ? 2500 : undefined); return { ok: true } as T; } }; const retry = new RetryingGoogleDriveTransport(delegate, { maximumAttempts: 3, baseDelayMs: 100, maximumDelayMs: 1000 }, async (ms) => { waits.push(ms); }, () => .5); await expect(retry.execute({ ...request, operation: "FILES_LIST" })).resolves.toEqual({ ok: true }); expect(waits).toEqual([2500, 250]); const terminal: GoogleDriveTransport = { async execute() { throw new GoogleDriveTransportError(403, ["forbidden"]); } }; let slept = false; await expect(new RetryingGoogleDriveTransport(terminal, { maximumAttempts: 3, baseDelayMs: 1, maximumDelayMs: 10 }, async () => { slept = true; }, () => 0).execute(request)).rejects.toBeDefined(); expect(slept).toBe(false); expect(parseRetryAfter("2", 0)).toBe(2000); });
  it("records hash-safe download audits and stops deterministic anomalies", async () => { const events: DownloadSecurityEvent[] = []; const monitor = new PilotDownloadSecurityMonitor("org", "connection", { expectedCorpusSize: 2, hardMaximumDownloads: 3, maximumExpansionRatio: 1.5, maximumBoundaryFailures: 1 }, { async append(event) { events.push(event); } }, () => new Date("2026-09-20T00:00:00Z")); const delegate: GoogleDriveTransport = { async execute<T>() { return new Uint8Array([1]) as T; } }; const audited = new AuditedGoogleDriveTransport(delegate, monitor); await audited.execute(request); await audited.execute(request); await audited.execute(request); await expect(audited.execute(request)).rejects.toMatchObject({ code: "DRIVE_DOWNLOAD_ANOMALY_STOP" }); expect(events).toHaveLength(6); expect(JSON.stringify(events)).not.toContain("file"); monitor.recordBoundaryFailure(); expect(() => monitor.recordBoundaryFailure()).toThrow("DRIVE_BOUNDARY_ANOMALY_STOP"); });
  it("persists isolated tenant-bound checkpoints and connection roots atomically", async () => { const directory = await mkdtemp(join(tmpdir(), "recoveria-pilot-")); const checkpoints = new LocalPersistentPilotCheckpointStore(directory); const checkpoint = { schemaVersion: 1, organizationId: "org", sourceType: "GOOGLE_DRIVE", sourceId: "connection", revision: "r1", entries: [] } as const; const first = await checkpoints.saveAtomically("org", "connection", checkpoint, null); expect(first.version).toBe(1); await expect(checkpoints.saveAtomically("org", "connection", checkpoint, null)).rejects.toThrow("CHECKPOINT_OPTIMISTIC_LOCK_CONFLICT"); await expect(checkpoints.saveAtomically("other", "connection", checkpoint, null)).rejects.toThrow("CHECKPOINT_SOURCE_BOUNDARY_MISMATCH"); const connections = new LocalPilotConnectionStore(directory); await connections.save({ organizationId: "org", connectionId: "connection", googleSubject: "subject", authorizedRootId: "root-id", authorizationState: "CONNECTED", grantedScopeState: "VALID" }); expect(await connections.load("org", "connection")).toMatchObject({ authorizedRootId: "root-id" }); expect(await connections.load("other", "connection")).toBeNull(); });
  it("keeps revocation state explicit and permits only literal true through the kill switch", async () => { expect(connectionStateForFailure(new DriveSourceFetchError("DRIVE_REVOKED", "AUTHORIZATION"))).toBe("REVOKED"); expect(connectionStateForFailure(new DriveSourceFetchError("DRIVE_PERMISSION_DENIED", "AUTHORIZATION"))).toBe("REAUTHORIZATION_REQUIRED"); const invalidValues: unknown[] = [false, undefined, null, "false", "0", "true", 0, 1, {}, []]; for (const enabled of invalidValues) { let executions = 0; const adversarialGate = { enabled } as PilotExecutionGate; await expect(runControlledPilot(adversarialGate, async () => { executions += 1; return "never"; })).rejects.toThrow("GOOGLE_DRIVE_PILOT_NOT_CONFIGURED"); expect(executions).toBe(0); } let validExecutions = 0; await expect(runControlledPilot({ enabled: true }, async () => { validExecutions += 1; return "synthetic-only"; })).resolves.toBe("synthetic-only"); expect(validExecutions).toBe(1); expect(() => assertPilotEnabled(DISABLED_GOOGLE_DRIVE_PILOT_GATE)).toThrow("GOOGLE_DRIVE_PILOT_NOT_CONFIGURED"); expect(SYNTHETIC_GOOGLE_DRIVE_PILOT).toMatchObject({ expectedRecords: 40, killSwitchEnabled: false, authorizationState: "DISCONNECTED", requiredScope: GOOGLE_DRIVE_READONLY_SCOPE }); });
});
