import { DriveSourceFetchError, type DriveChangePage, type DriveConnection, type DriveFileDescriptor, type DriveFilePage, type GoogleDriveClientPort } from "./google-drive-source-contract";

export const DEFAULT_DRIVE_PILOT_MAX_DOCUMENT_BYTES = 25 * 1024 * 1024;
export type PilotConnectionState = "DISCONNECTED" | "AUTHORIZATION_PENDING" | "CONNECTED" | "REAUTHORIZATION_REQUIRED" | "REVOKED";
export interface DriveCredentialProvider { getValidAccessToken(connectionId: string): Promise<{ readonly value: string }> }
export type GoogleDriveOperation = "FILES_LIST" | "FILES_GET" | "FILES_DOWNLOAD" | "CHANGES_START_TOKEN" | "CHANGES_LIST";
export const READ_ONLY_GOOGLE_DRIVE_OPERATIONS: readonly GoogleDriveOperation[] = ["FILES_LIST", "FILES_GET", "FILES_DOWNLOAD", "CHANGES_START_TOKEN", "CHANGES_LIST"];
export interface GoogleDriveTransportRequest { readonly operation: GoogleDriveOperation; readonly accessToken: string; readonly parameters: Readonly<Record<string, string | number | boolean | undefined>>; readonly maximumResponseBytes?: number }
export interface GoogleDriveTransport { execute<T>(request: GoogleDriveTransportRequest): Promise<T> }
export class GoogleDriveTransportError extends Error { constructor(readonly status?: number, readonly reasons: readonly string[] = [], readonly network?: "TIMEOUT" | "INTERRUPTED") { super("GOOGLE_DRIVE_TRANSPORT_FAILURE"); } }

interface GoogleFile { readonly id?: string; readonly name?: string; readonly mimeType?: string; readonly size?: string; readonly modifiedTime?: string; readonly parents?: readonly string[]; readonly trashed?: boolean; readonly driveId?: string; readonly shortcutDetails?: { readonly targetId?: string } }
interface GoogleFileList { readonly files?: readonly GoogleFile[]; readonly nextPageToken?: string }
interface GoogleChange { readonly fileId?: string; readonly removed?: boolean; readonly file?: GoogleFile }
interface GoogleChangeList { readonly changes?: readonly GoogleChange[]; readonly nextPageToken?: string; readonly newStartPageToken?: string }

const quotaReasons = new Set(["rateLimitExceeded", "userRateLimitExceeded", "quotaExceeded", "sharingRateLimitExceeded", "dailyLimitExceeded"]);
export function normalizeGoogleDriveError(error: unknown): DriveSourceFetchError {
  if (!(error instanceof GoogleDriveTransportError)) return new DriveSourceFetchError("DRIVE_TRANSPORT_INTERRUPTED", "RETRYABLE");
  if (error.network) return new DriveSourceFetchError(`DRIVE_${error.network}`, "RETRYABLE");
  const reason = error.reasons[0];
  if (error.status === 401 || error.reasons.some((item) => item === "authError" || item === "invalidCredentials" || item === "revokedAuthorization")) return new DriveSourceFetchError("DRIVE_REAUTHORIZATION_REQUIRED", "AUTHORIZATION");
  if (error.status === 403 && error.reasons.some((item) => quotaReasons.has(item))) return new DriveSourceFetchError("DRIVE_RATE_OR_QUOTA_LIMIT", "RETRYABLE");
  if (error.status === 403) return new DriveSourceFetchError("DRIVE_PERMISSION_DENIED", "AUTHORIZATION");
  if (error.status === 429 || (error.status !== undefined && error.status >= 500 && error.status <= 599)) return new DriveSourceFetchError(`DRIVE_${error.status}`, "RETRYABLE");
  if ((error.status === 400 || error.status === 404) && error.reasons.some((item) => item === "invalidPageToken" || item === "pageTokenExpired")) return new DriveSourceFetchError("DRIVE_CURSOR_EXPIRED", "CURSOR_EXPIRED");
  if (error.status === 404) return new DriveSourceFetchError("DRIVE_FILE_NOT_FOUND_OR_INACCESSIBLE", "TERMINAL");
  return new DriveSourceFetchError(`DRIVE_${reason ?? error.status ?? "INVALID_REQUEST"}`, "TERMINAL");
}

export class RealGoogleDriveClient implements GoogleDriveClientPort {
  readonly #metadata = new Map<string, GoogleFile>(); readonly #membership = new Map<string, boolean>();
  constructor(private readonly connection: DriveConnection, private readonly credentials: DriveCredentialProvider, private readonly transport: GoogleDriveTransport, private readonly maximumDocumentBytes = DEFAULT_DRIVE_PILOT_MAX_DOCUMENT_BYTES) {}
  async #execute<T>(operation: GoogleDriveOperation, parameters: GoogleDriveTransportRequest["parameters"], maximumResponseBytes?: number): Promise<T> { if (this.connection.authorizationState !== "AUTHORIZED" && this.connection.authorizationState !== "CONNECTED") throw new DriveSourceFetchError("DRIVE_REAUTHORIZATION_REQUIRED", "AUTHORIZATION"); try { const token = await this.credentials.getValidAccessToken(this.connection.connectionId); return await this.transport.execute<T>({ operation, accessToken: token.value, parameters, maximumResponseBytes }); } catch (error) { if (error instanceof DriveSourceFetchError) throw error; throw normalizeGoogleDriveError(error); } }
  #rawToDescriptor(file: GoogleFile): DriveFileDescriptor { if (!file.id || !file.name || !file.mimeType) throw new DriveSourceFetchError("DRIVE_METADATA_INCOMPLETE", "TERMINAL"); const size = file.size === undefined ? 0 : Number(file.size); if (!Number.isSafeInteger(size) || size < 0) throw new DriveSourceFetchError("DRIVE_METADATA_INVALID_SIZE", "TERMINAL"); return { fileId: file.id, displayName: file.name, locator: `drive-item:${file.id}`, mimeType: file.mimeType, size, modifiedAt: file.modifiedTime, kind: file.mimeType === "application/vnd.google-apps.folder" ? "FOLDER" : file.mimeType === "application/vnd.google-apps.shortcut" ? "SHORTCUT" : "FILE", trashed: file.trashed, corpusRootId: this.connection.authorizedRootId, shortcutTargetId: file.shortcutDetails?.targetId }; }
  async #metadataFor(fileId: string): Promise<GoogleFile> { const cached = this.#metadata.get(fileId); if (cached) return cached; const file = await this.#execute<GoogleFile>("FILES_GET", { fileId, supportsAllDrives: true, fields: "id,name,mimeType,size,modifiedTime,parents,trashed,driveId,shortcutDetails" }); this.#metadata.set(fileId, file); return file; }
  async #isMember(file: GoogleFile): Promise<boolean> { if (!file.id) throw new DriveSourceFetchError("DRIVE_METADATA_INCOMPLETE", "TERMINAL"); const prior = this.#membership.get(file.id); if (prior !== undefined) return prior; const visited = new Set<string>(); let current = file; for (let depth = 0; depth < 128; depth++) { if (!current.id || current.trashed) { this.#membership.set(file.id, false); return false; } if (current.driveId !== this.connection.sharedDriveId && (current.driveId || this.connection.sharedDriveId)) throw new DriveSourceFetchError("DRIVE_SHARED_DRIVE_BOUNDARY_MISMATCH", "TERMINAL"); if (current.id === this.connection.authorizedRootId) { this.#membership.set(file.id, true); return true; } if (visited.has(current.id)) throw new DriveSourceFetchError("DRIVE_ANCESTRY_CYCLE", "TERMINAL"); visited.add(current.id); if (!current.parents?.length) { this.#membership.set(file.id, false); return false; } if (current.parents.length !== 1) throw new DriveSourceFetchError("DRIVE_ANCESTRY_UNPROVEN", "TERMINAL"); current = await this.#metadataFor(current.parents[0]!); } throw new DriveSourceFetchError("DRIVE_ANCESTRY_DEPTH_EXCEEDED", "TERMINAL"); }
  async listFiles(input: { rootId: string; sharedDriveId?: string; pageToken?: string }): Promise<DriveFilePage> { if (input.rootId !== this.connection.authorizedRootId || input.sharedDriveId !== this.connection.sharedDriveId) throw new DriveSourceFetchError("DRIVE_CORPUS_BOUNDARY_VIOLATION", "TERMINAL"); if (!input.pageToken) { this.#metadata.clear(); this.#membership.clear(); } const response = await this.#execute<GoogleFileList>("FILES_LIST", { pageToken: input.pageToken, spaces: "drive", corpora: input.sharedDriveId ? "drive" : "user", driveId: input.sharedDriveId, includeItemsFromAllDrives: Boolean(input.sharedDriveId), supportsAllDrives: true, fields: "nextPageToken,files(id,name,mimeType,size,modifiedTime,parents,trashed,driveId,shortcutDetails)" }); const files: DriveFileDescriptor[] = []; for (const file of response.files ?? []) { if (file.id) { this.#metadata.set(file.id, file); this.#membership.delete(file.id); } if (await this.#isMember(file)) files.push(this.#rawToDescriptor(file)); } return { files, ...(response.nextPageToken ? { nextPageToken: response.nextPageToken } : {}) }; }
  async getMetadata(fileId: string): Promise<DriveFileDescriptor> { const file = await this.#metadataFor(fileId); if (!(await this.#isMember(file))) throw new DriveSourceFetchError("DRIVE_CORPUS_BOUNDARY_VIOLATION", "TERMINAL"); return this.#rawToDescriptor(file); }
  async readPdfContent(fileId: string): Promise<Uint8Array> { this.#metadata.clear(); this.#membership.clear(); const file = await this.#metadataFor(fileId); if (!(await this.#isMember(file))) throw new DriveSourceFetchError("DRIVE_CORPUS_BOUNDARY_VIOLATION", "TERMINAL"); if (file.mimeType !== "application/pdf") throw new DriveSourceFetchError("DRIVE_UNSUPPORTED_MIME", "TERMINAL"); const size = Number(file.size); if (!Number.isSafeInteger(size) || size < 0) throw new DriveSourceFetchError("DRIVE_METADATA_INVALID_SIZE", "TERMINAL"); if (size > this.maximumDocumentBytes) throw new DriveSourceFetchError("DRIVE_DOCUMENT_TOO_LARGE", "TERMINAL"); const bytes = await this.#execute<Uint8Array>("FILES_DOWNLOAD", { fileId, alt: "media", supportsAllDrives: true }, this.maximumDocumentBytes); if (bytes.byteLength > this.maximumDocumentBytes) throw new DriveSourceFetchError("DRIVE_DOCUMENT_TOO_LARGE", "TERMINAL"); return bytes; }
  async getStartPageToken(input: { rootId: string; sharedDriveId?: string }): Promise<string> { if (input.rootId !== this.connection.authorizedRootId || input.sharedDriveId !== this.connection.sharedDriveId) throw new DriveSourceFetchError("DRIVE_CORPUS_BOUNDARY_VIOLATION", "TERMINAL"); const response = await this.#execute<{ startPageToken?: string }>("CHANGES_START_TOKEN", { supportsAllDrives: true, driveId: input.sharedDriveId }); if (!response.startPageToken) throw new DriveSourceFetchError("DRIVE_CURSOR_MALFORMED", "CURSOR_INVALID"); return response.startPageToken; }
  async listChanges(input: { rootId: string; sharedDriveId?: string; pageToken: string }): Promise<DriveChangePage> { if (input.rootId !== this.connection.authorizedRootId || input.sharedDriveId !== this.connection.sharedDriveId) throw new DriveSourceFetchError("DRIVE_CORPUS_BOUNDARY_VIOLATION", "TERMINAL"); const response = await this.#execute<GoogleChangeList>("CHANGES_LIST", { pageToken: input.pageToken, spaces: "drive", supportsAllDrives: true, includeItemsFromAllDrives: Boolean(input.sharedDriveId), driveId: input.sharedDriveId, fields: "nextPageToken,newStartPageToken,changes(fileId,removed,file(id,name,mimeType,size,modifiedTime,parents,trashed,driveId,shortcutDetails))" }); const changes = []; for (const item of response.changes ?? []) { if (!item.fileId) throw new DriveSourceFetchError("DRIVE_CHANGE_MALFORMED", "TERMINAL"); if (item.removed || item.file?.trashed) { changes.push({ fileId: item.fileId, removed: true }); continue; } if (!item.file) continue; this.#metadata.set(item.fileId, item.file); this.#membership.delete(item.fileId); if (!(await this.#isMember(item.file))) continue; changes.push({ fileId: item.fileId, removed: false, file: this.#rawToDescriptor(item.file) }); } return { changes, ...(response.nextPageToken ? { nextPageToken: response.nextPageToken } : {}), ...(response.newStartPageToken ? { newStartPageToken: response.newStartPageToken } : {}) }; }
}

export interface SanitizedDriveTelemetry { readonly operation: GoogleDriveOperation; readonly outcome: "SUCCESS" | "FAILURE"; readonly durationMs: number; readonly itemCount?: number; readonly errorKind?: string }
export function sanitizeDriveTelemetry(event: SanitizedDriveTelemetry): SanitizedDriveTelemetry { return { operation: event.operation, outcome: event.outcome, durationMs: event.durationMs, ...(event.itemCount === undefined ? {} : { itemCount: event.itemCount }), ...(event.errorKind === undefined ? {} : { errorKind: event.errorKind }) }; }
