import { describe, expect, it } from "vitest";
import { GoogleDriveSource, type DriveConnection } from "./google-drive-source-contract";
import { assertGoogleDrivePilotConfigured } from "./google-drive-pilot-command";
import { InMemoryProductionSourceCheckpointStore } from "./production-source-checkpoint-port";
import { DEFAULT_DRIVE_PILOT_MAX_DOCUMENT_BYTES, GoogleDriveTransportError, READ_ONLY_GOOGLE_DRIVE_OPERATIONS, RealGoogleDriveClient, normalizeGoogleDriveError, sanitizeDriveTelemetry, type DriveCredentialProvider, type GoogleDriveOperation, type GoogleDriveTransport, type GoogleDriveTransportRequest } from "./real-google-drive-client";
import { IncrementalCorpusProcessor } from "./incremental-corpus-processor";
import { DeterministicDocumentUnderstandingProvider } from "./document-understanding-provider";

const connection: DriveConnection = { organizationId: "org-a", connectionId: "connection-a", googleSubject: "subject-a", authorizedRootId: "root", authorizationState: "CONNECTED" };
const credentials: DriveCredentialProvider = { async getValidAccessToken() { return { value: "test-token-sentinel" }; } };
class MockTransport implements GoogleDriveTransport {
  readonly requests: GoogleDriveTransportRequest[] = []; readonly handlers = new Map<GoogleDriveOperation, (request: GoogleDriveTransportRequest) => unknown>();
  async execute<T>(request: GoogleDriveTransportRequest): Promise<T> { this.requests.push(request); const handler = this.handlers.get(request.operation); if (!handler) throw new Error(`missing ${request.operation}`); return handler(request) as T; }
}
const root = { id: "root", name: "Root", mimeType: "application/vnd.google-apps.folder", parents: [] as string[], trashed: false };
const pdf = (id: string, parents: string[] = ["root"], overrides: Record<string, unknown> = {}) => ({ id, name: `${id}.pdf`, mimeType: "application/pdf", size: "100", modifiedTime: "2026-09-20T00:00:00Z", parents, trashed: false, ...overrides });
function invoicePdf(number: number): Uint8Array { const lines = ["FACTURA B", `Nro: 0007-${String(number).padStart(8, "0")}`, "Fecha: 15/07/2026", "CUIT: 30-70000000-1", `Razon Social: Consorcio ${number % 6}`, `CUIT: 30-${String(80_000_000 + number % 6).padStart(8, "0")}-1`, "Domicilio: Calle 1", "Moneda: Peso", "TOTAL 100000.00"]; const commands = lines.map((line, index) => `BT /F1 10 Tf 40 ${800 - index * 22} Td (${line}) Tj ET`).join("\n"); const objects = ["<< /Type /Catalog /Pages 2 0 R >>", "<< /Type /Pages /Kids [3 0 R] /Count 1 >>", "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 600 840] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>", `<< /Length ${Buffer.byteLength(commands)} >>\nstream\n${commands}\nendstream`, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"]; let value = "%PDF-1.4\n"; const offsets = [0]; objects.forEach((body, index) => { offsets.push(Buffer.byteLength(value)); value += `${index + 1} 0 obj\n${body}\nendobj\n`; }); const xref = Buffer.byteLength(value); value += `xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, "0")} 00000 n \n`).join("")}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`; return new TextEncoder().encode(value); }
const transportFor = (files: unknown[]): MockTransport => { const transport = new MockTransport(); const metadata = new Map<string, unknown>([["root", root], ["folder", { id: "folder", name: "Nested", mimeType: "application/vnd.google-apps.folder", parents: ["root"], trashed: false }], ["outside", { id: "outside", name: "Outside", mimeType: "application/vnd.google-apps.folder", parents: [], trashed: false }], ...files.map((file) => [(file as { id: string }).id, file] as [string, unknown])]); transport.handlers.set("FILES_LIST", () => ({ files })); transport.handlers.set("FILES_GET", ({ parameters }) => { const item = metadata.get(String(parameters.fileId)); if (!item) throw new GoogleDriveTransportError(404, ["notFound"]); return item; }); transport.handlers.set("FILES_DOWNLOAD", () => new Uint8Array([1, 2, 3])); transport.handlers.set("CHANGES_START_TOKEN", () => ({ startPageToken: "change-1" })); transport.handlers.set("CHANGES_LIST", () => ({ changes: [], newStartPageToken: "change-2" })); return transport; };
function mutableFixture() { const transport = new MockTransport(); const metadata = new Map<string, Record<string, unknown>>([["root", root], ["folder", { id: "folder", name: "Folder", mimeType: "application/vnd.google-apps.folder", parents: ["root"], trashed: false }], ["folder-2", { id: "folder-2", name: "Folder 2", mimeType: "application/vnd.google-apps.folder", parents: ["root"], trashed: false }], ["outside", { id: "outside", name: "Outside", mimeType: "application/vnd.google-apps.folder", parents: [], trashed: false }], ["file", pdf("file", ["folder"])]]) as Map<string, Record<string, unknown>>; let listed = metadata.get("file")!; let downloads = 0; transport.handlers.set("FILES_LIST", () => ({ files: [listed] })); transport.handlers.set("FILES_GET", ({ parameters }) => { const item = metadata.get(String(parameters.fileId)); if (!item) throw new GoogleDriveTransportError(404, ["notFound"]); return item; }); transport.handlers.set("FILES_DOWNLOAD", () => { downloads += 1; return new Uint8Array([1]); }); return { transport, metadata, setListed(value: Record<string, unknown>) { listed = value; }, downloads: () => downloads }; }

describe("RealGoogleDriveClient offline security boundary", () => {
  it("proves direct and nested membership, excludes moved-out files, and uses IDs rather than paths", async () => { const files = [pdf("direct"), pdf("nested", ["folder"]), pdf("outside-file", ["outside"], { name: "root/fake.pdf" })]; const client = new RealGoogleDriveClient(connection, credentials, transportFor(files)); const page = await client.listFiles({ rootId: "root" }); expect(page.files.map(({ fileId }) => fileId)).toEqual(["direct", "nested"]); });
  it("fails closed on cycles, conflicting ancestry, inaccessible parents, shared-drive mismatch, and trashed ancestors", async () => {
    for (const [file, extra, code] of [[pdf("cycle", ["cycle"]), [], "DRIVE_ANCESTRY_CYCLE"], [pdf("multi", ["root", "outside"]), [], "DRIVE_ANCESTRY_UNPROVEN"], [pdf("missing", ["missing-parent"]), [], "DRIVE_FILE_NOT_FOUND_OR_INACCESSIBLE"], [pdf("shared", ["root"], { driveId: "other" }), [], "DRIVE_SHARED_DRIVE_BOUNDARY_MISMATCH"], [pdf("under-trash", ["trash"]), [{ id: "trash", name: "Trash", mimeType: "application/vnd.google-apps.folder", parents: ["root"], trashed: true }], null]] as const) {
      const client = new RealGoogleDriveClient(connection, credentials, transportFor([file, ...extra])); if (code) await expect(client.listFiles({ rootId: "root" })).rejects.toMatchObject({ code }); else expect((await client.listFiles({ rootId: "root" })).files).toEqual([]);
    }
  });
  it("downloads only proven PDFs within the configured size ceiling", async () => { const file = pdf("a"); const transport = transportFor([file]); const client = new RealGoogleDriveClient(connection, credentials, transport, 1_024); await client.listFiles({ rootId: "root" }); await expect(client.readPdfContent("a")).resolves.toEqual(new Uint8Array([1, 2, 3])); expect(transport.requests.at(-1)).toMatchObject({ operation: "FILES_DOWNLOAD", maximumResponseBytes: 1_024, parameters: { alt: "media" } }); const oversized = new RealGoogleDriveClient(connection, credentials, transportFor([pdf("big", ["root"], { size: "1025" })]), 1_024); await expect(oversized.readPdfContent("big")).rejects.toMatchObject({ code: "DRIVE_DOCUMENT_TOO_LARGE" }); expect(DEFAULT_DRIVE_PILOT_MAX_DOCUMENT_BYTES).toBe(25 * 1024 * 1024); });
  it("re-proves the complete fresh ancestry chain immediately before every download", async () => {
    const scenarios: Array<{ mutate(fixture: ReturnType<typeof mutableFixture>): void; allowed: boolean }> = [
      { mutate: ({ metadata }) => metadata.set("file", pdf("file", ["outside"])), allowed: false },
      { mutate: ({ metadata }) => metadata.set("folder", { ...metadata.get("folder")!, parents: ["outside"] }), allowed: false },
      { mutate: ({ metadata, transport }) => transport.handlers.set("FILES_GET", ({ parameters }) => { if (parameters.fileId === "folder") throw new GoogleDriveTransportError(403, ["forbidden"]); const item = metadata.get(String(parameters.fileId)); if (!item) throw new GoogleDriveTransportError(404, ["notFound"]); return item; }), allowed: false },
      { mutate: ({ metadata }) => metadata.set("file", { ...metadata.get("file")!, trashed: true }), allowed: false },
      { mutate: ({ metadata }) => metadata.set("folder", { ...metadata.get("folder")!, trashed: true }), allowed: false },
      { mutate: () => undefined, allowed: true },
      { mutate: ({ metadata }) => metadata.set("file", pdf("file", ["folder-2"])), allowed: true },
    ];
    for (const scenario of scenarios) { const fixture = mutableFixture(); const client = new RealGoogleDriveClient(connection, credentials, fixture.transport); await client.listFiles({ rootId: "root" }); scenario.mutate(fixture); if (scenario.allowed) await expect(client.readPdfContent("file")).resolves.toEqual(new Uint8Array([1])); else await expect(client.readPdfContent("file")).rejects.toBeDefined(); expect(fixture.downloads()).toBe(scenario.allowed ? 1 : 0); }
  });
  it("does not carry stale ancestry across sequential authoritative runs", async () => { const fixture = mutableFixture(); const client = new RealGoogleDriveClient(connection, credentials, fixture.transport); const source = new GoogleDriveSource(connection, client); expect((await source.discover()).map(({ sourceDocumentId }) => sourceDocumentId)).toEqual(["file"]); const moved = pdf("file", ["outside"]); fixture.metadata.set("file", moved); fixture.setListed(moved); expect(await source.discover()).toEqual([]); await expect(client.readPdfContent("file")).rejects.toBeDefined(); expect(fixture.downloads()).toBe(0); });
  it("normalizes status plus Google reasons", () => { const cases: Array<[GoogleDriveTransportError, string, boolean]> = [[new GoogleDriveTransportError(401, ["authError"]), "AUTHORIZATION", false], [new GoogleDriveTransportError(403, ["forbidden"]), "AUTHORIZATION", false], [new GoogleDriveTransportError(403, []), "AUTHORIZATION", false], [new GoogleDriveTransportError(403, ["unknownReason"]), "AUTHORIZATION", false], [new GoogleDriveTransportError(403, ["dailyLimitExceeded"]), "RETRYABLE", true], [new GoogleDriveTransportError(403, ["rateLimitExceeded"]), "RETRYABLE", true], [new GoogleDriveTransportError(403, ["userRateLimitExceeded"]), "RETRYABLE", true], [new GoogleDriveTransportError(403, ["quotaExceeded"]), "RETRYABLE", true], [new GoogleDriveTransportError(429), "RETRYABLE", true], [new GoogleDriveTransportError(404, ["notFound"]), "TERMINAL", false], [new GoogleDriveTransportError(400, ["badRequest"]), "TERMINAL", false], [new GoogleDriveTransportError(undefined, [], "TIMEOUT"), "RETRYABLE", true], [new GoogleDriveTransportError(500), "RETRYABLE", true], [new GoogleDriveTransportError(502), "RETRYABLE", true], [new GoogleDriveTransportError(503), "RETRYABLE", true], [new GoogleDriveTransportError(401, ["revokedAuthorization"]), "AUTHORIZATION", false], [new GoogleDriveTransportError(400, ["invalidPageToken"]), "CURSOR_EXPIRED", false]]; for (const [error, kind, retryable] of cases) expect(normalizeGoogleDriveError(error)).toMatchObject({ kind, retryable }); });
  it("translates start tokens and paginated changes without making them authoritative", async () => { const transport = transportFor([pdf("a")]); transport.handlers.set("CHANGES_LIST", ({ parameters }) => parameters.pageToken === "change-1" ? { changes: [{ fileId: "a", removed: false, file: pdf("a") }], nextPageToken: "change-page-2" } : { changes: [{ fileId: "gone", removed: true }], newStartPageToken: "change-3" }); const source = new GoogleDriveSource(connection, new RealGoogleDriveClient(connection, credentials, transport)); const cursor = await source.currentCursor(); const changes = await source.discoverChanges(cursor); expect(changes).toMatchObject({ status: "VALID", removedSourceDocumentIds: ["gone"], nextCursor: { value: "change-3" } }); expect(changes.changedDocuments.map(({ sourceDocumentId }) => sourceDocumentId)).toEqual(["a"]); });
  it("handles real-transport pagination, 1,001 records, cycles, limits, later failures, duplicates, and metadata churn", async () => {
    const files = Array.from({ length: 1_001 }, (_, index) => pdf(`f-${index}`)); const transport = transportFor([...files, root]); transport.handlers.set("FILES_LIST", ({ parameters }) => { const offset = Number(parameters.pageToken ?? 0); return { files: files.slice(offset, offset + 250), ...(offset + 250 < files.length ? { nextPageToken: String(offset + 250) } : {}) }; }); const source = new GoogleDriveSource(connection, new RealGoogleDriveClient(connection, credentials, transport)); expect((await source.discover()).length).toBe(1_001);
    const repeated = transportFor([pdf("a")]); repeated.handlers.set("FILES_LIST", () => ({ files: [pdf("a")], nextPageToken: "A" })); await expect(new GoogleDriveSource(connection, new RealGoogleDriveClient(connection, credentials, repeated)).discover()).rejects.toMatchObject({ code: "DRIVE_PAGINATION_TOKEN_CYCLE" });
    const cycle = transportFor([]); cycle.handlers.set("FILES_LIST", ({ parameters }) => ({ files: [], nextPageToken: parameters.pageToken === undefined ? "A" : parameters.pageToken === "A" ? "B" : "A" })); await expect(new GoogleDriveSource(connection, new RealGoogleDriveClient(connection, credentials, cycle)).discover()).rejects.toMatchObject({ code: "DRIVE_PAGINATION_TOKEN_CYCLE" });
    let calls = 0; const guarded = transportFor([]); guarded.handlers.set("FILES_LIST", () => ({ files: [], nextPageToken: String(++calls) })); await expect(new GoogleDriveSource(connection, new RealGoogleDriveClient(connection, credentials, guarded)).discover()).rejects.toMatchObject({ code: "DRIVE_PAGINATION_LIMIT_EXCEEDED" });
    const later = transportFor([pdf("a")]); later.handlers.set("FILES_LIST", ({ parameters }) => { if (parameters.pageToken) throw new GoogleDriveTransportError(503); return { files: [pdf("a")], nextPageToken: "later" }; }); await expect(new GoogleDriveSource(connection, new RealGoogleDriveClient(connection, credentials, later)).discover()).rejects.toMatchObject({ code: "DRIVE_503" });
    const duplicate = transportFor([pdf("a")]); duplicate.handlers.set("FILES_LIST", ({ parameters }) => ({ files: [pdf("a")], ...(parameters.pageToken ? {} : { nextPageToken: "2" }) })); expect((await new GoogleDriveSource(connection, new RealGoogleDriveClient(connection, credentials, duplicate)).discover()).length).toBe(1);
    const changing = transportFor([pdf("a")]); changing.handlers.set("FILES_LIST", ({ parameters }) => ({ files: [parameters.pageToken ? pdf("a", ["root"], { modifiedTime: "later" }) : pdf("a")], ...(parameters.pageToken ? {} : { nextPageToken: "2" }) })); await expect(new GoogleDriveSource(connection, new RealGoogleDriveClient(connection, credentials, changing)).discover()).rejects.toMatchObject({ code: "DRIVE_PAGINATION_METADATA_CONFLICT" });
  }, 30_000);
  it("has a read-only operation surface", () => { expect(READ_ONLY_GOOGLE_DRIVE_OPERATIONS).toEqual(["FILES_LIST", "FILES_GET", "FILES_DOWNLOAD", "CHANGES_START_TOKEN", "CHANGES_LIST"]); expect(READ_ONLY_GOOGLE_DRIVE_OPERATIONS.some((value) => /CREATE|UPDATE|DELETE|UPLOAD|MOVE|TRASH|PERMISSION/.test(value))).toBe(false); });
  it("redacts undeclared sensitive telemetry fields", () => { const unsafe = { operation: "FILES_LIST", outcome: "FAILURE", durationMs: 12, itemCount: 3, errorKind: "AUTHORIZATION", accessToken: "secret", refreshToken: "secret", authorization: "Bearer secret", oauthCode: "code", filename: "private.pdf", fileId: "id", rootId: "root", googleSubject: "subject", bytes: "raw", invoice: "raw" } as const; const output = sanitizeDriveTelemetry(unsafe); expect(output).toEqual({ operation: "FILES_LIST", outcome: "FAILURE", durationMs: 12, itemCount: 3, errorKind: "AUTHORIZATION" }); expect(JSON.stringify(output)).not.toMatch(/secret|private|subject|invoice|Bearer/); });
  it("keeps the pilot command disabled and checkpoint writes atomic", async () => { expect(() => assertGoogleDrivePilotConfigured()).toThrow("GOOGLE_DRIVE_PILOT_NOT_CONFIGURED"); const store = new InMemoryProductionSourceCheckpointStore(); const key = { organizationId: "org-a", sourceType: "GOOGLE_DRIVE", sourceId: "connection-a" } as const; const checkpoint = { schemaVersion: 1, ...key, revision: "r1", entries: [] } as const; const first = await store.saveAtomically(key, "connection-a", checkpoint, null); expect(first.version).toBe(1); await expect(store.saveAtomically(key, "connection-a", checkpoint, null)).rejects.toThrow("CHECKPOINT_OPTIMISTIC_LOCK_CONFLICT"); });
  it("rehearses the mocked 40-record pilot without network", async () => { const bytes = new Map<string, Uint8Array>(); const files: Record<string, unknown>[] = Array.from({ length: 37 }, (_, index) => { const content = invoicePdf(index); bytes.set(`pilot-${index}`, content); return pdf(`pilot-${index}`, ["root"], { size: String(index === 36 ? DEFAULT_DRIVE_PILOT_MAX_DOCUMENT_BYTES + 1 : content.length) }); }); const unsupportedMetadata = { modifiedTime: "2026-09-20T00:00:00Z", parents: ["root"], trashed: false }; files.push({ id: "native", name: "native", mimeType: "application/vnd.google-apps.document", size: "0", ...unsupportedMetadata }, { id: "shortcut", name: "shortcut", mimeType: "application/vnd.google-apps.shortcut", size: "0", shortcutDetails: { targetId: "outside" }, ...unsupportedMetadata }, { id: "text", name: "notes.txt", mimeType: "text/plain", size: "10", ...unsupportedMetadata }); const transport = transportFor(files); transport.handlers.set("FILES_DOWNLOAD", ({ parameters }) => bytes.get(String(parameters.fileId))!); const processor = new IncrementalCorpusProcessor(new DeterministicDocumentUnderstandingProvider()); const source = new GoogleDriveSource(connection, new RealGoogleDriveClient(connection, credentials, transport)); const first = await processor.process(source); expect(first.report.metrics).toMatchObject({ documentsDiscovered: 40, documentsUnderstood: 39, documentsReused: 0, documentsFailed: 1 }); expect(first.report.summary).toMatchObject({ documentsWithResult: 39, documentsUnsupported: 3, documentsClassifiedAsInvoice: 36 }); const second = await processor.process(source, first.checkpoint); expect(second.report.metrics).toMatchObject({ documentsDiscovered: 40, documentsUnderstood: 0, documentsReused: 39, documentsFailed: 1 }); });
});
