type Configuration = { issuer: string; externalAudience: string; subject: string; provider: string; serviceAccount: string; cloudRunAudience: string };
const decode = (token: string): Record<string, unknown> => { try { const parts = token.split("."); if (parts.length !== 3) throw new Error(); return JSON.parse(Buffer.from(parts[1], "base64url").toString()) as Record<string, unknown>; } catch { throw new Error("WIF_ASSERTION_INVALID"); } };
export function wifConfiguration(environment: NodeJS.ProcessEnv): Configuration {
  const read = (key: string) => { const value = environment[key]?.trim(); if (!value) throw new Error("STAGING_WIF_NOT_CONFIGURED"); return value; };
  return { issuer: read("RECOVERIA_VERCEL_OIDC_ISSUER"), externalAudience: read("RECOVERIA_VERCEL_OIDC_AUDIENCE"), subject: read("RECOVERIA_VERCEL_OIDC_SUBJECT"), provider: read("RECOVERIA_GCP_WIF_PROVIDER"), serviceAccount: read("RECOVERIA_GCP_SERVICE_ACCOUNT"), cloudRunAudience: read("RECOVERIA_STAGING_API_AUDIENCE") };
}
export async function cloudRunIdToken(assertion: string, configuration: Configuration, fetcher: typeof fetch = fetch): Promise<string> {
  const claim = decode(assertion); if (claim.iss !== configuration.issuer || claim.aud !== configuration.externalAudience || claim.sub !== configuration.subject || typeof claim.exp !== "number" || claim.exp * 1000 <= Date.now()) throw new Error("WIF_ASSERTION_REJECTED");
  const sts = await fetcher("https://sts.googleapis.com/v1/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ audience: configuration.provider, grant_type: "urn:ietf:params:oauth:grant-type:token-exchange", requested_token_type: "urn:ietf:params:oauth:token-type:access_token", scope: "https://www.googleapis.com/auth/cloud-platform", subject_token_type: "urn:ietf:params:oauth:token-type:jwt", subject_token: assertion }) });
  if (!sts.ok) throw new Error("WIF_STS_REJECTED"); const exchange = await sts.json() as { access_token?: unknown; expires_in?: unknown; token_type?: unknown }; if (typeof exchange.access_token !== "string" || exchange.token_type !== "Bearer" || typeof exchange.expires_in !== "number" || exchange.expires_in <= 0 || exchange.expires_in > 3600) throw new Error("WIF_STS_INVALID");
  const response = await fetcher(`https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/${encodeURIComponent(configuration.serviceAccount)}:generateIdToken`, { method: "POST", headers: { authorization: `Bearer ${exchange.access_token}`, "content-type": "application/json" }, body: JSON.stringify({ audience: configuration.cloudRunAudience, includeEmail: false }) });
  if (!response.ok) throw new Error("WIF_IMPERSONATION_REJECTED"); const result = await response.json() as { token?: unknown }; if (typeof result.token !== "string") throw new Error("WIF_ID_TOKEN_INVALID"); const identity = decode(result.token); if (identity.aud !== configuration.cloudRunAudience || typeof identity.exp !== "number" || identity.exp * 1000 <= Date.now()) throw new Error("WIF_ID_TOKEN_INVALID"); return result.token;
}
