import{describe,expect,it}from"vitest";import{attentionOfToday}from"./attention";import{DEFAULT_OPERATIONAL_POLICY}from"./policy";import{portfolioIntelligence}from"./portfolio";import{prioritizeCase}from"./prioritize";import{FOREIGN_CASE,PHASE4_TRUTH}from"@/test/fixtures/phase-4-truth-set";
describe("Phase 4 truth set",()=>{
 it.each(PHASE4_TRUTH)("routes $case.id",t=>{const r=prioritizeCase(t.case,DEFAULT_OPERATIONAL_POLICY);expect(r.attentionType).toBe(t.attentionType);expect(r.priorityTier).toBe(t.tier);expect(r.reasons.map(x=>x.code)).toEqual(expect.arrayContaining([...t.requiredReasons]));expect(r.blockers.map(x=>x.code)).toEqual(expect.arrayContaining([...t.requiredBlockers]));expect(t.excluded).not.toContain(r.attentionType);});
 it("grounds every reason and blocker in supplied evidence",()=>{for(const t of PHASE4_TRUTH){const allowed=new Set(Object.values(t.case).flatMap(v=>typeof v==="object"&&v&&"evidenceRefs"in v?(v as {evidenceRefs:string[]}).evidenceRefs:[]));const r=prioritizeCase(t.case,DEFAULT_OPERATIONAL_POLICY);expect([...r.reasons,...r.blockers].every(x=>x.evidenceRefs.length>0&&x.evidenceRefs.every(ref=>allowed.has(ref)))).toBe(true);}});
 it("makes the missed promise outrank the largest active promise",()=>{const items=attentionOfToday("org-recoveria-synthetic",PHASE4_TRUTH.map(x=>x.case),DEFAULT_OPERATIONAL_POLICY);expect(items[0].caseId).toBe("legal");expect(items.findIndex(x=>x.caseId==="missed")).toBeGreaterThanOrEqual(0);expect(items.some(x=>x.caseId==="largest-active")).toBe(false);});
 it("is deterministic and bounded",()=>{const cases=PHASE4_TRUTH.map(x=>x.case);expect(attentionOfToday("org-recoveria-synthetic",cases,DEFAULT_OPERATIONAL_POLICY)).toEqual(attentionOfToday("org-recoveria-synthetic",[...cases].reverse(),DEFAULT_OPERATIONAL_POLICY));expect(attentionOfToday("org-recoveria-synthetic",cases,DEFAULT_OPERATIONAL_POLICY).length).toBeLessThanOrEqual(8);});
 it("prevents cross-tenant leakage",()=>expect(attentionOfToday("org-recoveria-synthetic",[...PHASE4_TRUTH.map(x=>x.case),FOREIGN_CASE],DEFAULT_OPERATIONAL_POLICY).some(x=>x.caseId==="foreign")).toBe(false));
 it("computes grouping, concentrations, oldest and operational cohorts",()=>{const p=portfolioIntelligence("org-recoveria-synthetic",PHASE4_TRUTH.map(x=>x.case));expect(p.totalOutstandingCents).toBe(1_320_000_000);expect(p.largestReceivables[0]).toEqual({caseId:"largest-active",outstandingCents:500_000_000});expect(p.oldestReceivables[0]).toEqual({caseId:"legal",daysOverdue:1500});expect(p.multipleOverdue).toContain("multi");expect(p.missedPromises).toEqual(["missed"]);expect(p.disputes).toEqual(["disputed"]);});
});
