"use client";
import { useState } from "react";
import Link from "next/link";
import { answerAgentQuestion, suggestedQuestions, type AgentTurn } from "@/lib/demo/agent";
import { demoModel as m } from "@/lib/demo/product-model";
import { EvidenceReference } from "@/components/evidence-inspector";

// Phase 4.7 — Agente RecoverIA. Deterministic, local, multi-turn question
// answering over the existing demo model. No external AI API call is made;
// every answer is generated by src/lib/demo/agent.ts from data already
// computed by the domain/operational-intelligence modules.
let turnCounter = 0;
const nextId = () => `turn-${(turnCounter += 1)}`;

export function AgentConsole() {
  const [turns, setTurns] = useState<readonly AgentTurn[]>([
    { id: nextId(), role: "agent", text: "Hola, soy el Agente RecoverIA. Puedo explicar prioridades, pagos informados y preparar borradores de seguimiento — siempre distinguiendo hechos, inferencias y lo que todavía no sabemos.", kind: "text" },
  ]);
  const [pending, setPending] = useState("");

  const ask = (question: string) => {
    if (!question.trim()) return;
    const answer = answerAgentQuestion(question);
    setTurns((prev) => [...prev, { id: nextId(), role: "user", text: question }, { id: nextId(), role: "agent", text: answer.text, kind: answer.kind, caseIds: answer.caseIds, invoiceIds: answer.invoiceIds }]);
    setPending("");
  };

  return <div className="agent-shell">
    <aside className="agent-suggestions">
      <h3>Preguntas sugeridas</h3>
      {suggestedQuestions.map((question) => <button key={question} onClick={() => ask(question)}>{question}</button>)}
    </aside>
    <div className="agent-conversation">
      <div className="agent-log" aria-live="polite">
        {turns.map((turn) => <div key={turn.id} className={`agent-turn ${turn.role}`}>
          {turn.text}
          {turn.caseIds && turn.caseIds.length > 0 && <div className="agent-case-chips">{turn.caseIds.slice(0, 6).map((id) => <Link key={id} href={`/casos/${id}`}>{m.cases.find((c) => c.id === id)?.entityName ?? id}</Link>)}</div>}
          {turn.invoiceIds && turn.invoiceIds.length > 0 && <div className="agent-evidence-references">{turn.invoiceIds.map((id) => <EvidenceReference invoiceId={id} key={id}>{m.invoices.find((invoice) => invoice.id === id)?.invoiceNumber ?? id}</EvidenceReference>)}</div>}
        </div>)}
      </div>
      <form className="agent-input" onSubmit={(e) => { e.preventDefault(); ask(pending); }}>
        <input value={pending} onChange={(e) => setPending(e.target.value)} placeholder="Preguntale algo al Agente RecoverIA" aria-label="Mensaje para el Agente RecoverIA" />
        <button type="submit" disabled={!pending.trim()}>Enviar</button>
      </form>
    </div>
  </div>;
}
