"use client";
import { useState } from "react";import Link from "next/link";import { Badge,date,money } from "@/components/ui";import { SortButton } from "@/components/sort-button";import { agingLabel,filterOptions,invoiceStatusLabel } from "@/lib/demo/presentation";import { sortInvoiceRows,type Direction,type InvoiceSort } from "@/lib/demo/list-controls";
export interface InvoiceRow{id:string;invoiceNumber:string;entityName:string;buildingName:string;issuedAt:string;dueAt:string;totalCents:number;outstandingCents:number;daysOverdue:number;aging:string;status:string;reviewRequired:boolean}
export function InvoiceList({rows}:{rows:readonly InvoiceRow[]}){
 const[filter,setFilter]=useState("ALL"),[key,setKey]=useState<InvoiceSort>("issued"),[order,setOrder]=useState<Direction>("desc");
 const change=(next:InvoiceSort)=>{if(next===key)setOrder(v=>v==="desc"?"asc":"desc");else{setKey(next);setOrder(next==="due"?"asc":"desc")}};
 const filtered=rows.filter(i=>filter==="ALL"?true:filter==="REVIEW"?i.reviewRequired:filter==="OLDEST"?i.aging==="365+":i.status===filter),sorted=sortInvoiceRows(filtered,key,order);
 return <><div className="filters" aria-label="Filtrar facturas">{filterOptions.map(([value,label])=><button aria-pressed={filter===value} className={filter===value?"active":""} onClick={()=>setFilter(value)} key={value}>{label}</button>)}</div>
 <label className="mobile-sort">Ordenar por<select value={`${key}-${order}`} onChange={e=>{const[k,o]=e.target.value.split("-")as[InvoiceSort,Direction];setKey(k);setOrder(o)}}><option value="issued-desc">Más recientes</option><option value="due-asc">Próximo vencimiento</option><option value="outstanding-desc">Mayor saldo</option><option value="age-desc">Más antiguas primero</option></select></label>
 <div className="table-wrap table-only"><table><thead><tr><th>Factura</th><th>Administración</th><th>Consorcio</th><th><SortButton label="Fecha" active={key==="issued"} direction={order} onClick={()=>change("issued")}/></th><th><SortButton label="Vencimiento" active={key==="due"} direction={order} onClick={()=>change("due")}/></th><th>Original</th><th><SortButton label="Pendiente" active={key==="outstanding"} direction={order} onClick={()=>change("outstanding")}/></th><th><SortButton label="Antigüedad" active={key==="age"} direction={order} onClick={()=>change("age")}/></th><th>Estado</th></tr></thead><tbody>{sorted.map(i=><tr key={i.id}><td><Link className="link" href={`/facturas/${i.id}`}>{i.invoiceNumber}</Link></td><td>{i.entityName}</td><td>{i.buildingName}</td><td>{date(i.issuedAt)}</td><td>{date(i.dueAt)}</td><td>{money(i.totalCents)}</td><td><strong>{money(i.outstandingCents)}</strong></td><td>{agingLabel(i.aging)}</td><td><Badge tone={i.reviewRequired?"review":i.status.toLowerCase()}>{i.reviewRequired?"Requiere revisión":invoiceStatusLabel(i.status)}</Badge></td></tr>)}</tbody></table></div>
 <div className="card-list">{sorted.map(i=><article className="row-card" key={i.id}><div className="row-card-top"><Link className="link" href={`/facturas/${i.id}`}>{i.invoiceNumber}</Link><Badge tone={i.reviewRequired?"review":i.status.toLowerCase()}>{i.reviewRequired?"Requiere revisión":invoiceStatusLabel(i.status)}</Badge></div><h3>{i.entityName}</h3><span>{i.buildingName}</span><strong className="amount">{money(i.outstandingCents)}</strong><div className="row-card-meta"><span>Vence {date(i.dueAt)}</span><span>{agingLabel(i.aging)}</span></div></article>)}</div></>;
}
