"use client";

import { CheckCircle2, Cloud, FolderOpen, LoaderCircle, RefreshCw, ShieldCheck } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import type { View } from "@/lib/view-types";

type Stage = "loading" | "connected" | "confirm" | "scanning" | "ready" | "error";
type SourceView = { id: string; health: string; rootDisplayName?: string; committedDocumentCount: number; reviewRequiredCount: number; lastSuccessfulSyncAt?: string };
type Summary = { documentsAnalyzed: number; uniqueDocuments: number; exactDuplicates: number; possibleDuplicates: number; detectedEntities: number; reviewRequired: number; documentsDiscovered?: number; documentsDownloaded?: number; documentsUnderstood?: number; documentsReused?: number; failures?: number; checkpointVersion?: number };
type PickerBootstrap = { apiKey: string; appId: string; accessToken: string; accessTokenExpiresAt: string; view: { enableSharedDrives: false } };
type PickerCallback = { action?: string; docs?: Array<{ id?: string }> };
type PickerApi = { Action: { PICKED: string }; ViewId: { FOLDERS: string }; DocsView: new (id: string) => { setIncludeFolders(value: boolean): unknown; setSelectFolderEnabled(value: boolean): unknown; setMimeTypes(value: string): unknown }; PickerBuilder: new () => { addView(view: unknown): unknown; setOAuthToken(value: string): unknown; setDeveloperKey(value: string): unknown; setAppId(value: string): unknown; setOrigin(value: string): unknown; setCallback(value: (data: PickerCallback) => void): unknown; build(): { setVisible(value: boolean): void } } };

declare global { interface Window { gapi?: { load(name: string, callback: () => void): void }; google?: { picker: PickerApi } } }

const CORE = "/api/staging";
const SYNC_INTENT_STORAGE_KEY = "recoveria.connected-source.sync-intent";
const SYNC_INTENT_SESSION_KEY = "recoveria.connected-source.sync-intent-session";
async function api<T>(path: string, options: RequestInit = {}): Promise<T> { const response = await fetch(`${CORE}${path}`, { ...options, credentials: "include", cache: "no-store" }); const body = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(body.error ?? "CONNECTED_SOURCE_REQUEST_FAILED"); return body; }
type FounderSession = { csrfToken: string; sessionBindingId: string; source: SourceView; lastSummary?: Summary };
let founderSessionBootstrap: Promise<FounderSession> | null = null;
function loadFounderSession(): Promise<FounderSession> { return founderSessionBootstrap ??= api<FounderSession>("/api/connected-sources/session").catch(error => { founderSessionBootstrap = null; throw error; }); }
function clearStoredSyncIntent(): void { sessionStorage.removeItem(SYNC_INTENT_STORAGE_KEY); sessionStorage.removeItem(SYNC_INTENT_SESSION_KEY); }
async function loadPicker(): Promise<PickerApi> { if (!window.gapi) await new Promise<void>((resolve, reject) => { const script = document.createElement("script"); script.src = "https://apis.google.com/js/api.js"; script.async = true; script.onload = () => resolve(); script.onerror = () => reject(new Error("GOOGLE_PICKER_SCRIPT_FAILED")); document.head.appendChild(script); }); await new Promise<void>((resolve, reject) => { if (!window.gapi) return reject(new Error("GOOGLE_PICKER_SCRIPT_FAILED")); window.gapi.load("picker", resolve); }); if (!window.google?.picker) throw new Error("GOOGLE_PICKER_UNAVAILABLE"); return window.google.picker; }

export function ConnectedSources({ setView }: { setView: (view: View) => void }) {
  const [stage, setStage] = useState<Stage>("loading"); const [csrf, setCsrf] = useState(""); const [sessionBindingId, setSessionBindingId] = useState(""); const [source, setSource] = useState<SourceView | null>(null); const [candidate, setCandidate] = useState<{ candidateId: string; displayName: string } | null>(null); const [summary, setSummary] = useState<Summary | null>(null); const [error, setError] = useState("");
  const syncIntentRef = useRef<string | null>(null);
  useEffect(() => { void loadFounderSession().then(result => { if (sessionStorage.getItem(SYNC_INTENT_STORAGE_KEY) && sessionStorage.getItem(SYNC_INTENT_SESSION_KEY) !== result.sessionBindingId) clearStoredSyncIntent(); setCsrf(result.csrfToken); setSessionBindingId(result.sessionBindingId); setSource(result.source); setSummary(result.lastSummary ?? null); setStage(result.source.committedDocumentCount > 0 ? "ready" : "connected"); }).catch(reason => { setError(reason instanceof Error ? reason.message : "No pudimos iniciar la sesión local"); setStage("error"); }); }, []);
  const chooseFolder = useCallback(async () => { try { setError(""); const bootstrap = await api<PickerBootstrap>("/api/connected-sources/picker"); const picker = await loadPicker(); const view = new picker.DocsView(picker.ViewId.FOLDERS); view.setIncludeFolders(true); view.setSelectFolderEnabled(true); view.setMimeTypes("application/vnd.google-apps.folder"); const builder = new picker.PickerBuilder(); builder.addView(view); builder.setOAuthToken(bootstrap.accessToken); builder.setDeveloperKey(bootstrap.apiKey); builder.setAppId(bootstrap.appId); builder.setOrigin(window.location.origin); builder.setCallback(data => { if (data.action !== picker.Action.PICKED) return; const folderId = data.docs?.[0]?.id; if (!folderId) return; void api<{ candidateId: string; displayName: string }>("/api/connected-sources/folder-candidate", { method: "POST", headers: { "Content-Type": "application/json", "X-CSRF-Token": csrf }, body: JSON.stringify({ folderId }) }).then(result => { setCandidate(result); setStage("confirm"); }).catch(reason => { setError(reason instanceof Error ? reason.message : "No pudimos validar la carpeta"); setStage("error"); }); }); builder.build().setVisible(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "No pudimos abrir Google Drive"); setStage("error"); } }, [csrf]);
  const runSync = useCallback(async () => { const storedIntent = sessionStorage.getItem(SYNC_INTENT_SESSION_KEY) === sessionBindingId ? sessionStorage.getItem(SYNC_INTENT_STORAGE_KEY) : null; const syncIntentId = syncIntentRef.current ?? storedIntent ?? crypto.randomUUID(); syncIntentRef.current = syncIntentId; sessionStorage.setItem(SYNC_INTENT_STORAGE_KEY, syncIntentId); sessionStorage.setItem(SYNC_INTENT_SESSION_KEY, sessionBindingId); try { setError(""); setStage("scanning"); for (;;) { const result = await api<{ outcome: { status: "RUNNING" | "SUCCEEDED" | "FAILED" }; summary?: Summary; source: SourceView }>("/api/connected-sources/sync", { method: "POST", headers: { "X-CSRF-Token": csrf, "X-Sync-Intent-Id": syncIntentId } }); if (result.outcome.status === "RUNNING") { await new Promise(resolve => setTimeout(resolve, 750)); continue; } if (result.outcome.status === "FAILED") { syncIntentRef.current = null; clearStoredSyncIntent(); throw new Error("CONNECTED_SOURCE_SYNC_FAILED"); } if (!result.summary) throw new Error("CONNECTED_SOURCE_SYNC_RESULT_MISSING"); setSummary(result.summary); setSource(result.source); setStage("ready"); syncIntentRef.current = null; clearStoredSyncIntent(); return; } } catch (reason) { if (reason instanceof Error && reason.message === "CONNECTED_SOURCE_SYNC_INTENT_BINDING_MISMATCH") { syncIntentRef.current = null; clearStoredSyncIntent(); } setError(reason instanceof Error ? reason.message : "La sincronización no pudo completarse"); setStage("error"); } }, [csrf, sessionBindingId]);
  const confirmAndScan = useCallback(async () => { if (!candidate) return; try { const result = await api<{ source: SourceView }>("/api/connected-sources/confirm", { method: "POST", headers: { "Content-Type": "application/json", "X-CSRF-Token": csrf }, body: JSON.stringify({ candidateId: candidate.candidateId }) }); setSource(result.source); await runSync(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No pudimos conectar la carpeta"); setStage("error"); } }, [candidate, csrf, runSync]);
  const connected = (stage !== "loading" && Boolean(source) && source?.health !== "NOT_CONFIGURED") || Boolean(candidate); const result = summary ?? (source?.committedDocumentCount ? { documentsAnalyzed: source.committedDocumentCount, uniqueDocuments: source.committedDocumentCount, exactDuplicates: 0, possibleDuplicates: 0, detectedEntities: 0, reviewRequired: source.reviewRequiredCount } : null);
  return <><div className="page-heading"><div><div className="eyebrow">CONFIGURACIÓN · FUENTES</div><h1>Fuentes conectadas</h1><p>Conectá la información que Recoveria usa para comprender tus documentos.</p></div></div><section className="source-layout"><article className="panel source-card"><div className="source-card-head"><div className="source-provider-icon"><Cloud size={22} /></div><div><span>GOOGLE DRIVE</span><h2>Documentos de facturación</h2></div><b className={`source-status ${connected ? "ok" : "neutral"}`}>{connected ? "Conectado" : "Preparando"}</b></div>
    {stage === "loading" && <div className="source-step"><LoaderCircle className="spin" size={27} /><h3>Preparando conexión segura…</h3><p>Validamos la sesión y la fuente sintética autorizada.</p></div>}
    {stage === "connected" && <div className="source-step"><CheckCircle2 className="source-success" size={28} /><h3>Google Drive conectado</h3><p>Elegí visualmente la carpeta que Recoveria debe analizar. No necesitás copiar identificadores.</p><button className="primary" onClick={() => void chooseFolder()}><FolderOpen size={16} /> Elegir carpeta</button></div>}
    {stage === "confirm" && candidate && <div className="source-confirm"><div><span>CARPETA SELECCIONADA</span><h3><FolderOpen size={18} /> {candidate.displayName}</h3><p>Recoveria leerá los documentos compatibles de esta carpeta, analizará las facturas automáticamente y mantendrá la fuente conectada.</p></div><div className="readonly-note"><ShieldCheck size={17} /><span><strong>Conexión de solo lectura</strong>Recoveria no puede editar, mover ni eliminar archivos.</span></div><button className="primary" onClick={() => void confirmAndScan()}>Conectar carpeta y analizar</button><button className="secondary" onClick={() => void chooseFolder()}>Elegir otra</button></div>}
    {stage === "scanning" && <div className="source-progress" role="status"><LoaderCircle className="spin" size={27} /><span>SINCRONIZACIÓN SEGURA</span><h3>Recoveria está trabajando…</h3><strong>Analizando documentos</strong><div><i style={{ width: "62%" }} /></div><p>Validamos la carpeta, analizamos facturas y conservamos la evidencia. Los documentos normales avanzan automáticamente.</p></div>}
    {stage === "ready" && result && <><div className="source-summary"><CheckCircle2 size={28} /><div><span>TRABAJO COMPLETADO</span><h3>Tus facturas están listas</h3></div><dl><div><dt>Documentos analizados</dt><dd>{result.documentsAnalyzed}</dd></div><div><dt>Documentos únicos</dt><dd>{result.uniqueDocuments}</dd></div><div><dt>Duplicados exactos</dt><dd>{result.exactDuplicates}</dd></div><div><dt>Requieren atención</dt><dd>{result.reviewRequired}</dd></div></dl><button className="primary" onClick={() => setView("facturas")}>Ver facturas</button></div><div className="source-management"><div><span>Carpeta</span><strong>{source?.rootDisplayName ?? candidate?.displayName ?? "Carpeta conectada"}</strong></div><div><span>Última sincronización</span><strong>{source?.lastSuccessfulSyncAt ? "Ahora" : "Completada"} · {result.documentsAnalyzed} documentos</strong></div><div><span>Estado</span><strong className={source?.health === "ERROR" ? undefined : "healthy"}>{source?.health === "ERROR" ? "Último resultado preservado" : "Actualizado"}</strong></div>{result.documentsReused !== undefined && <div className="source-reuse-note">{result.documentsReused} documentos sin cambios reutilizados · {result.documentsUnderstood ?? 0} requirieron nuevo análisis</div>}<div className="source-actions"><button className="secondary" onClick={() => void runSync()}><RefreshCw size={15} /> Sincronizar ahora</button><button className="secondary" onClick={() => void chooseFolder()}>Cambiar carpeta</button></div></div></>}
    {stage === "error" && <div className="source-step"><h3>No pudimos completar esta acción</h3><p>{error || "La fuente permanece protegida y no se aplicaron cambios parciales."}</p><button className="secondary" onClick={() => window.location.reload()}>Reintentar sesión</button></div>}
  </article><aside className="source-truth"><span>QUÉ APORTA ESTA FUENTE</span><h3>Verdad documental</h3><p>Google Drive permite identificar documentos, importes nominales, fechas, entidades candidatas y evidencia.</p><p>No determina saldos pendientes, pagos ni deuda actual.</p></aside></section></>;
}
