"use client";
import { useEffect, useState } from "react";
import { AlertCircle, ChevronRight, FileText, LoaderCircle, X } from "lucide-react";
import { classificationLabel, confidenceLabel, documentaryMoney, productSurfaceDocumentUrl, productSurfaceGet, type EvidenceField, type ProductEvidence, type ProductInvoice, type ProductRelationships } from "@/lib/product-surface";
import { useEscapeKey } from "@/lib/use-escape";

const fields: readonly { key: EvidenceField; label: string }[] = [{ key: "invoiceNumber", label: "Número de factura" }, { key: "issueDate", label: "Fecha de emisión" }, { key: "documentedDueDate", label: "Vencimiento documentado" }, { key: "documentedNominalTotalCents", label: "Importe nominal documentado" }, { key: "currency", label: "Moneda" }, { key: "entityCandidate", label: "Entidad candidata" }];
type DetailTab = "data" | "document" | "evidence";

function formatField(invoice: ProductInvoice, key: EvidenceField): string {
  const value = invoice[key].value;
  if (key === "documentedNominalTotalCents") return documentaryMoney(value as number | null, invoice.currency.value);
  if ((key === "issueDate" || key === "documentedDueDate") && value) return new Intl.DateTimeFormat("es-AR").format(new Date(`${value}T12:00:00`));
  return value === null ? "No identificado" : String(value);
}

export function ProductDocumentDetail({ documentId, onClose }: { documentId: string; onClose: () => void }) {
  const [invoice, setInvoice] = useState<ProductInvoice | null>(null); const [error, setError] = useState(false); const [tab, setTab] = useState<DetailTab>("data"); const [selected, setSelected] = useState<EvidenceField | null>(null); const [evidence, setEvidence] = useState<ProductEvidence | null>(null); const [relationships, setRelationships] = useState<ProductRelationships | null>(null); const [advanced, setAdvanced] = useState(false); const [previewUrl, setPreviewUrl] = useState<string | null>(null); const [previewState, setPreviewState] = useState<"idle" | "loading" | "ready" | "error">("idle"); const [previewAttempt, setPreviewAttempt] = useState(0);
  useEscapeKey(onClose);
  useEffect(() => { const controller = new AbortController(); productSurfaceGet<ProductInvoice>(`invoices/${encodeURIComponent(documentId)}`, controller.signal).then(setInvoice).catch((failure) => { if (!(failure instanceof DOMException && failure.name === "AbortError")) setError(true); }); return () => controller.abort(); }, [documentId]);
  useEffect(() => { if (!selected) { setEvidence(null); return; } const controller = new AbortController(); productSurfaceGet<ProductEvidence>(`invoices/${encodeURIComponent(documentId)}/evidence?field=${selected}`, controller.signal).then(setEvidence).catch(() => setEvidence(null)); return () => controller.abort(); }, [documentId, selected]);
  useEffect(() => { if (!advanced || relationships) return; productSurfaceGet<ProductRelationships>(`invoices/${encodeURIComponent(documentId)}/relationships`).then(setRelationships).catch(() => setRelationships(null)); }, [advanced, documentId, relationships]);
  useEffect(() => {
    if (tab !== "document" || previewUrl) return;
    const controller = new AbortController(); setPreviewState("loading");
    fetch(productSurfaceDocumentUrl(documentId), { cache: "no-store", headers: { accept: "application/pdf" }, signal: controller.signal }).then(async (response) => {
      if (!response.ok || response.headers.get("content-type")?.split(";")[0] !== "application/pdf") throw new Error("PREVIEW_UNAVAILABLE");
      const url = URL.createObjectURL(await response.blob()); setPreviewUrl(url); setPreviewState("ready");
    }).catch((failure) => { if (!(failure instanceof DOMException && failure.name === "AbortError")) setPreviewState("error"); });
    return () => controller.abort();
  }, [documentId, previewAttempt, previewUrl, tab]);
  useEffect(() => () => { if (previewUrl) URL.revokeObjectURL(previewUrl); }, [previewUrl]);

  return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer product-drawer invoice-workspace" onClick={(event) => event.stopPropagation()} aria-label="Detalle documental de factura">
    {!invoice && !error && <div className="product-state"><LoaderCircle className="spin" size={22} /><strong>Cargando documento…</strong></div>}
    {error && <div className="product-state error"><strong>No pudimos abrir este documento</strong><button className="secondary" onClick={onClose}>Volver</button></div>}
    {invoice && <><div className="drawer-head invoice-detail-head"><div><span>FACTURA DOCUMENTADA</span><h2>{invoice.invoiceNumber.value ?? "Sin número identificado"}</h2><p>{invoice.source.displayName}</p></div><button onClick={onClose} aria-label="Cerrar"><X size={19} /></button></div>
      <nav className="invoice-detail-tabs" aria-label="Secciones de factura">{([['data','Datos'],['document','Documento'],['evidence','Evidencia']] as const).map(([key,label]) => <button key={key} className={tab === key ? "active" : ""} aria-current={tab === key ? "page" : undefined} onClick={() => setTab(key)}>{label}</button>)}</nav>
      <div className="invoice-detail-body">
        {tab === "data" && <><div className="drawer-stats documentary"><div><span>Importe documentado</span><strong>{documentaryMoney(invoice.documentedNominalTotalCents.value, invoice.currency.value)}</strong></div><div><span>Confianza</span><strong>{confidenceLabel[invoice.confidenceSummary]}</strong></div><div><span>Revisión</span><strong>{invoice.reviewStatus.required ? "Requerida" : "Sin revisión"}</strong></div></div>
          <section className="cw-section"><span className="cw-label">DATOS DEL DOCUMENTO</span><div className="product-field-list">{fields.map(({ key, label }) => { const field = invoice[key]; return <button key={key} onClick={() => { setSelected(key); setTab("evidence"); }} disabled={!field.evidenceAvailable}><span><small>{label}</small><strong>{formatField(invoice, key)}</strong>{field.classification !== "FACT" && <em>{classificationLabel[field.classification]}</em>}</span><span className="field-confidence">{confidenceLabel[field.confidence]}{field.evidenceAvailable && <ChevronRight size={15} />}</span></button>; })}</div><p className="quiet-note">El importe nominal documentado no representa deuda, saldo pendiente ni estado de pago.</p></section>
          <section className="cw-section"><span className="cw-label">ORIGEN Y REVISIÓN</span><div className="review-summary"><span>Google Drive</span><span>{invoice.reviewStatus.reasonCount} señales</span><span>{invoice.relationships.proposalCount} relaciones propuestas</span>{invoice.duplicateStatus !== "NONE" && <span>{invoice.duplicateStatus === "EXACT_DOCUMENT_DUPLICATE" ? "Duplicado exacto" : "Posible duplicado"}</span>}</div>{invoice.relationships.proposalCount + invoice.relationships.unmatchedSignalCount > 0 && <button className="secondary advanced-toggle" onClick={() => setAdvanced((value) => !value)}>{advanced ? "Ocultar relaciones" : "Ver relaciones relevantes"}</button>}{advanced && <div className="relationship-detail">{!relationships && <span>Cargando relaciones…</span>}{relationships?.proposals.map((item, index) => <div key={`${item.kind}-${item.relatedDocumentId}-${index}`}><strong>{item.kind.replaceAll("_", " ")}</strong><span>{item.status} · Confianza {confidenceLabel[item.confidence].toLowerCase()}</span>{item.contradictingSignals.map((signal) => <p key={signal}>{signal}</p>)}</div>)}{relationships?.unmatchedSignals.map((item) => <div key={`${item.kind}-${item.reason}`}><strong>{item.kind.replaceAll("_", " ")}</strong><p>{item.reason}</p></div>)}</div>}</section></>}
        {tab === "document" && <section className="document-preview" aria-label="Documento original"><div className="document-preview-head"><div><FileText size={18} /><span><strong>Documento original</strong><small>PDF de origen · Solo lectura</small></span></div><span>{invoice.source.displayName}</span></div>{previewState === "loading" && <div className="product-state"><LoaderCircle className="spin" size={22} /><strong>Cargando PDF original…</strong><span>Verificando identidad e integridad documental.</span></div>}{previewState === "error" && <div className="product-state error"><AlertCircle size={22} /><strong>Documento original no disponible</strong><span>La factura y su evidencia permanecen disponibles.</span><button className="secondary" onClick={() => { setPreviewState("idle"); setPreviewAttempt((value) => value + 1); }}>Reintentar</button></div>}{previewUrl && <iframe src={previewUrl} title={`Documento original ${invoice.invoiceNumber.value ?? invoice.source.displayName}`} />}</section>}
        {tab === "evidence" && <section className="evidence-workspace"><div className="evidence-field-nav"><span className="cw-label">CAMPO DOCUMENTAL</span>{fields.map(({ key, label }) => <button key={key} className={selected === key ? "active" : ""} onClick={() => setSelected(key)} disabled={!invoice[key].evidenceAvailable}><span>{label}</span><strong>{formatField(invoice,key)}</strong></button>)}</div><div className="evidence-body product-evidence">{!selected && <div className="product-state"><FileText size={21} /><strong>Elegí un campo</strong><span>Vas a ver su clasificación, extracto y ubicación en el PDF.</span></div>}{selected && <><div className="evidence-summary"><span>{fields.find(({ key }) => key === selected)?.label}</span><strong>{formatField(invoice, selected)}</strong>{evidence && <div><span className={`epistemic ${evidence.classification.toLowerCase()}`}>{classificationLabel[evidence.classification]}</span><span>Confianza {confidenceLabel[evidence.confidence].toLowerCase()}</span></div>}</div>{!evidence && <div className="product-state"><LoaderCircle className="spin" size={20} /><span>Cargando evidencia…</span></div>}{evidence?.observations.length === 0 && <div className="product-state"><strong>No hay evidencia puntual disponible</strong><span>El campo permanece visible con su estado de incertidumbre.</span></div>}{evidence?.observations.map((observation) => <article className="source-observation" key={observation.observationId}><div><span>Página {observation.page}</span><span>Confianza {confidenceLabel[observation.confidence].toLowerCase()}</span></div><blockquote>{observation.excerpt}</blockquote><small>Región {Math.round(observation.region.x)}, {Math.round(observation.region.y)} · {Math.round(observation.region.width)} × {Math.round(observation.region.height)}</small></article>)}</>}<div className="evidence-source"><FileText size={16} /><span>{invoice.source.displayName}</span></div></div></section>}
      </div></>}
  </aside></div>;
}
