import{readFile}from"node:fs/promises";import path from"node:path";import{describe,expect,it}from"vitest";import{filterCaseRows,filterImportRows,sortCaseRows,sortInvoiceRows,sortPortfolioRows}from"./list-controls";import{importDemo}from"./import-model";import{demoModel}from"./product-model";
const caseRows=()=>demoModel.cases.map(c=>({caseId:c.id,priorityTier:c.recommendation.priorityTier,attentionIndex:(()=>{const i=demoModel.attention.findIndex(x=>x.caseId===c.id);return i<0?Number.MAX_SAFE_INTEGER:i})(),outstandingCents:c.outstandingCents.value,dispute:c.dispute.value,promise:c.promise.value,missingInformation:c.recommendation.attentionType==="REVIEW_ENTITY"||c.recommendation.attentionType==="ADD_CONTACT"}));
describe("Phase 4.7C product polish",()=>{
 it("orders every critical case above lower priorities by default",()=>{const rows=sortCaseRows(caseRows(),"priority","desc"),lastCritical=Math.max(...rows.map((r,i)=>r.priorityTier==="CRITICAL"?i:-1)),firstLower=rows.findIndex(r=>r.priorityTier!=="CRITICAL");expect(lastCritical).toBeLessThan(firstLower)});
 it("preserves Attention-of-Today order within the same tier",()=>{const rows=sortCaseRows(caseRows(),"priority","desc").filter(r=>r.priorityTier==="CRITICAL");expect(rows.map(r=>r.attentionIndex)).toEqual([...rows.map(r=>r.attentionIndex)].sort((a,b)=>a-b))});
 it("sorts portfolio rows by outstanding, overdue and invoice count",()=>{const rows=demoModel.entities.map(e=>({name:e.displayName,outstandingCents:e.outstandingCents,overdueCents:e.overdueCents,invoiceCount:e.invoices.length}));for(const key of ["outstanding","overdue","invoices"]as const){const sorted=sortPortfolioRows(rows,key,"desc");expect(sorted[0][key==="invoices"?"invoiceCount":key==="overdue"?"overdueCents":"outstandingCents"]).toBeGreaterThanOrEqual(sorted.at(-1)![key==="invoices"?"invoiceCount":key==="overdue"?"overdueCents":"outstandingCents"])} });
 it("provides a true oldest-first invoice sort",()=>{const sorted=sortInvoiceRows(demoModel.invoices,"age","desc");expect(sorted[0].daysOverdue).toBe(Math.max(...demoModel.invoices.map(i=>i.daysOverdue)));expect(sorted[0].id).toBe("i09")});
 it("filters critical, disputed, missed-promise and missing-information cases",()=>{const rows=caseRows();expect(filterCaseRows(rows,"critical").every(r=>r.priorityTier==="CRITICAL")).toBe(true);expect(filterCaseRows(rows,"dispute").every(r=>r.dispute)).toBe(true);expect(filterCaseRows(rows,"missedPromise").every(r=>r.promise==="MISSED")).toBe(true);expect(filterCaseRows(rows,"missingInformation").every(r=>r.missingInformation)).toBe(true)});
 it("filters import review and unprocessed states",async()=>{const{batch}=await importDemo();expect(filterImportRows(batch.results,"review").every(r=>r.status==="REVIEW_REQUIRED")).toBe(true);expect(filterImportRows(batch.results,"unprocessed").every(r=>r.status==="FAILED"||r.status==="UNSUPPORTED")).toBe(true)});
 it("shows open cases on administration detail",async()=>{const source=await readFile(path.join(process.cwd(),"src/app/cartera/[entityId]/page.tsx"),"utf8");expect(source).toContain("CASOS ABIERTOS");expect(source).toContain("/casos/${c.id}")});
 it("links invoices to a valid administration",async()=>{const source=await readFile(path.join(process.cwd(),"src/app/facturas/[invoiceId]/page.tsx"),"utf8");expect(source).toContain("/cartera/${invoice.administrationId}")});
 it("links cases to their administration and back to priorities",async()=>{const source=await readFile(path.join(process.cwd(),"src/app/casos/[caseId]/page.tsx"),"utf8");expect(source).toContain("/cartera/${c.administrationId}");expect(source).toContain("Volver a prioridades")});
 it("provides a branded Spanish not-found page",async()=>{const source=await readFile(path.join(process.cwd(),"src/app/not-found.tsx"),"utf8");expect(source).toContain("No encontramos esta página");expect(source).toContain("Volver al inicio")});
 it("preserves financial values and tenant isolation",()=>{expect(demoModel.summary.totalOutstandingCents).toBe(830_000_000);expect(demoModel.summary.totalOverdueCents).toBe(810_000_000);expect(demoModel.cases.every(c=>c.organizationId===demoModel.organization.id)).toBe(true)});
 it("keeps interaction code independent from Client Zero",async()=>{for(const file of ["src/lib/demo/list-controls.ts","src/components/case-list.tsx","src/components/invoice-list.tsx","src/components/import-list.tsx"]){const source=await readFile(path.join(process.cwd(),file),"utf8");expect(source).not.toMatch(/client-zero|\.private/i)}});
});
